--Created on 17 Nov 2011
-- Procedure to delete fr_number and its  associated data
-- To run this procedure, just type exec delete_fr_number('XXXXX') where XXXX = fr_number
create or replace
PROCEDURE DELETE_FR_NUMBER 
(
  P_FR_NUMBER IN VARCHAR2  
) AS 

V_SQLERM VARCHAR2(100);
BEGIN
  FOR C_REC IN (SELECT FR_ID FROM FR_NUMBER WHERE FR_NUMBER = P_FR_NUMBER)
  LOOP
    FOR C1_REC IN (SELECT FEATURE_ID FROM FEATURE WHERE FR_ID = C_REC.FR_ID)
    LOOP
      FOR C2_REC IN (SELECT SAMPLE_ID FROM SAMPLE WHERE FEATURE_ID = C1_REC.FEATURE_ID)
      LOOP
        FOR C3_REC IN (SELECT RECORD_ID FROM RECORD WHERE SAMPLE_ID = C2_REC.SAMPLE_ID)
        LOOP
        -- USING RECORD ID
          FOR C4_REC IN (SELECT RECORD_ID FROM ADOPTION WHERE RECORD_ID = C3_REC.RECORD_ID)
          LOOP
             DELETE FROM ADOPTOR WHERE RECORD_ID = C4_REC.RECORD_ID;
          END LOOP; -- C4_REC
          DELETE FROM ADOPTION WHERE RECORD_ID = C3_REC.RECORD_ID;
          DELETE FROM PALEONTOLOGY WHERE RECORD_ID = C3_REC.RECORD_ID;
          DELETE FROM RECORD_META WHERE RECORD_ID = C3_REC.RECORD_ID;
        END LOOP; -- C3REC
        -- USING SAMPLE ID
        DELETE FROM RECORD WHERE SAMPLE_ID = C2_REC.SAMPLE_ID;
        DELETE FROM SENT_TO WHERE SAMPLE_ID = C2_REC.SAMPLE_ID;
        DELETE FROM RELATIONSHIP WHERE SAMPLE_ID = C2_REC.SAMPLE_ID;
        DELETE FROM SEDIMENTARY_FEATURE WHERE SAMPLE_ID = C2_REC.SAMPLE_ID;
        DELETE FROM COLLECTOR WHERE SAMPLE_ID = C2_REC.SAMPLE_ID;
        DELETE FROM SAMPLE_META WHERE SAMPLE_ID = C2_REC.SAMPLE_ID;
      END LOOP; -- C2REC
      -- USING FEATURE ID
      DELETE FROM RELATIONSHIP WHERE RELATED_FEATURE_ID = C1_REC.FEATURE_ID;
      DELETE FROM FOLDER_CONTENT WHERE FEATURE_ID = C1_REC.FEATURE_ID;
      DELETE FROM FEATURE_META WHERE FEATURE_ID = C1_REC.FEATURE_ID;
      DELETE FROM SAMPLE WHERE FEATURE_ID = C1_REC.FEATURE_ID;
    END LOOP; -- C1REC
    -- USING FR ID
    DELETE FROM FEATURE WHERE FR_ID = C_REC.FR_ID;
  END LOOP; -- CREC
  -- USING FR NUMBER
  DELETE FROM FR_NUMBER WHERE FR_NUMBER = P_FR_NUMBER;
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
    BEGIN
      V_SQLERM := SQLERRM;
      ROLLBACK;
      RAISE_APPLICATION_ERROR(-20000,V_SQLERM);
    END;
END DELETE_FR_NUMBER;