variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode -ntp --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  GIT_STRATEGY: clone
  TZ: "Pacific/Auckland"

image: maven:3-openjdk-8

stages:
  - build
  - test
  - release
  - deploy

default:
  before_script:
    - cp $settings_xml ~/.m2/settings.xml
    
initial-build:
  tags:
    - docker
  stage: build
  except:
    - master
  script: 
    - mvn $MAVEN_CLI_OPTS -Pjenkins-build clean deploy
    
integration-tests:
  tags:
    - docker
  stage: test
  script: 
    - mvn $MAVEN_CLI_OPTS integration-test
  artifacts:
    paths:
      - public
    expire_in: 1 week
    reports:
      junit:
        - fred-main-webapp/target/surefire-reports/TEST-*.xml
        - fred-acceptance-tests/target/failsafe-reports/TEST-*.xml
         
release:
  tags:
    - docker
  stage: release
  only:
    - master
  script:
    - git config user.name "\"$GITLAB_USER_NAME\""
    - git config user.email "\"$GITLAB_USER_EMAIL\""
    - git config http.sslverify false
    - git remote set-url --push origin "https://gitlab-project-token:$release_token@git.gns.cri.nz/$CI_PROJECT_PATH.git"
    - git config pull.ff only
    - cp $settings_xml ~/.m2/settings.xml
    - mvn $MAVEN_CLI_OPTS gitflow:release-start
    - mvn $MAVEN_CLI_OPTS gitflow:release-finish

deploy-dev:
  tags:
    - docker
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -Pjenkins-build -DdeploymentURL=$data_dev_url:$tomcat_paleo_port/manager/text tomcat7:redeploy
    - mvn $MAVEN_CLI_OPTS clean verify -Pdevelopment
  when: manual
  
deploy-uat:
  tags:
    - docker
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -Pjenkins-build -DdeploymentURL=$data_uat_url:$tomcat_paleo_port/manager/text tomcat7:redeploy
    - mvn $MAVEN_CLI_OPTS clean verify -Puat
  when: manual
