<project name="fred" default="package">
	<target name="package" depends="compile">
		<jar destfile="fred.jar" basedir="src" includes="nz/**/*" excludes="**/*.java" />
		<ant dir=".." target="db-check">
			<property name="build.webxml" value="FRED/Fred_Webapp/WEB-INF/web.xml FRED/Fred_Webapp/META-INF/context.xml" />
		</ant>
		<war warfile="../ROOT.war" basedir="Fred_Webapp" webxml="Fred_Webapp/WEB-INF/web.xml" excludes="WEB-INF,WEB-INF/**/*">
			<lib dir=".">
				<include name="fred.jar" />
			</lib>
		</war>
		<war warfile="../fred.war" basedir="Redirect_Webapp" webxml="Redirect_Webapp/WEB-INF/web.xml" excludes="WEB-INF,WEB-INF/**/*" />
	</target>
	<target name="compile">
		<javac debug="true" srcdir="src" destdir="src">
			<classpath>
				<fileset dir="../lib">
					<include name="itext-1.4.jar" />
					<include name="junit.jar" />
					<include name="hibernate2.jar" />
					<include name="servlet-api.jar" />
					<include name="jsp-api.jar" />
					<include name="cglib-full-2.0.2.jar" />
				</fileset>
				<fileset dir="..">
					<include name="gol.jar" />
					<include name="gol-db.jar" />
					<include name="gol-core.jar" />
					<include name="gol-html.jar" />
					<include name="gol-spatial.jar" />
					<include name="gol-dataaccess.jar" />
					<include name="gol-test.jar" />
					<include name="gol-auth.jar" />
					<include name="gol-dbimpl.jar" />
					<include name="gol-web.jar" />
					<include name="gol-querybuilder.jar" />
				</fileset>
			</classpath>
		</javac>
	</target>
</project>