<project name="fred" default="package">
	<target name="package" depends="compile">
		<jar destfile="fred.jar" basedir="." includes="nz/**/*" excludes="**/*.java" />
		<ant dir=".." target="db-check">
			<property name="build.webxml" value="FRED/Fred_Webapp/WEB-INF/web.xml FRED/Fred_Webapp/META-INF/context.xml" />
		</ant>
		<war warfile="../fred.war" basedir="Fred_Webapp" webxml="Fred_Webapp/WEB-INF/web.xml" excludes="WEB-INF,WEB-INF/**/*">
			<lib dir=".">
				<include name="fred.jar" />
			</lib>
		</war>
	</target>
	<target name="compile">
		<javac debug="true" srcdir="." destdir=".">
			<classpath>
				<fileset dir="/opt/jdk/jre/lib/ext">
					<include name="*.jar" />
				</fileset>
				<fileset dir="/usr/local/build">
					<include name="gol.jar" />
					<include name="gol-test.jar" />
				</fileset>
			</classpath>
		</javac>
	</target>
</project>