<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>nz.cri.gns</groupId>
  <artifactId>fred</artifactId>
  <packaging>war</packaging>
  <version>2.0.0-SNAPSHOT</version>

  <name>Fossil Record Electronic Database</name>
  <url>http://fred.org.nz</url>
  
  <organization>
      <name>GNS Science Ltd</name>
      <url>http://www.gns.cri.nz</url>
  </organization>
  

  <dependencies>

    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>servlet-api</artifactId>
      <version>2.5</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>javax.servlet.jsp</groupId>
      <artifactId>jsp-api</artifactId>
      <version>2.1</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.lowagie</groupId>
      <artifactId>itext</artifactId>
      <version>1.4</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.esri</groupId>
      <artifactId>sde-sdk</artifactId>
      <version>9.3</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.esri</groupId>
      <artifactId>sde-pe-sdk</artifactId>
      <version>9.3</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>net.sf</groupId>
      <artifactId>hibernate</artifactId>
      <version>2.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>nz.cri.gns</groupId>
      <artifactId>gol-querybuilder</artifactId>
      <version>2.0.0-RELEASE</version>
    </dependency>
    <dependency>
      <groupId>nz.cri.gns</groupId>
      <artifactId>gol-dataaccess</artifactId>
      <version>2.0.0-RELEASE</version>
    </dependency>
    <dependency>
      <groupId>nz.cri.gns</groupId>
      <artifactId>gol-dbcp</artifactId>
      <version>2.0.0-RELEASE</version>
    </dependency>
    <dependency>
      <groupId>nz.cri.gns</groupId>
      <artifactId>gol-auth</artifactId>
      <version>2.0.0-RELEASE</version>
    </dependency>
    <dependency>
      <groupId>nz.cri.gns</groupId>
      <artifactId>gol-web</artifactId>
      <version>2.0.0-RELEASE</version>
    </dependency>
    <dependency>
      <groupId>nz.cri.gns</groupId>
      <artifactId>gol</artifactId>
      <version>2.0.0-RELEASE</version>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-cglib-repack</artifactId>
      <version>2.1_3</version>
    </dependency>
    <dependency>
      <groupId>net.sf.ehcache</groupId>
      <artifactId>ehcache</artifactId>
      <version>1.5.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.0.2</version>
        <configuration>
          <source>1.5</source>
          <target>1.5</target>
        </configuration>
      </plugin>
    </plugins>
    <finalName>fred</finalName>
  </build>
    <description>Interim FRED Mavenisation.</description>
</project>
