CREATE OR REPLACE TRIGGER Pal_List_Seq_Trg
BEFORE INSERT ON Pal_List
REFERENCING NEW AS new
FOR EACH ROW
WHEN (new.Pal_List_ID IS NULL)
DECLARE
  ok INTEGER;
  newID NUMBER;
BEGIN
  ok := 1;
  WHILE ok > 0 LOOP
    SELECT Pal_List_Seq.NEXTVAL INTO newID FROM DUAL;
    SELECT COUNT(*) INTO ok FROM Pal_List WHERE Pal_List_ID = newID;
  END LOOP;
  :NEW.Pal_List_ID := newID;
END;
/