CREATE OR REPLACE TRIGGER Record_Seq_Trg
BEFORE INSERT ON Record
REFERENCING NEW AS new
FOR EACH ROW
WHEN (new.Record_ID IS NULL)
DECLARE
  ok INTEGER;
  newID NUMBER;
BEGIN
  ok := 1;
  WHILE ok > 0 LOOP
    SELECT Record_Seq.NEXTVAL INTO newID FROM DUAL;
    SELECT COUNT(*) INTO ok FROM Record WHERE Record_ID = newID;
  END LOOP;
  :NEW.Record_ID := newID;
END;
/