package nz.cri.gns.fred.model;

import java.util.Date;
import java.util.Set;

public interface Feature extends Audited, Comparable<Feature> {

	public Integer getFeatureId();
    public void setFeatureId(Integer featureId);
    public Integer getSiteId();
    public void setSiteId(Integer siteId);
    public String getLocality();
    public void setLocality(String locality);
    public Integer getOrigSystemId();
    public void setOrigSystemId(Integer origSystemId);
    public String getOrigCoord();
    public void setOrigCoord(String origCoord);
    public Integer getMapYear();
    public void setMapYear(Integer mapYear);
    public String getCoordComments();
    public void setCoordComments(String coordComments);
    public String getFeatureType();
    public void setFeatureType(String featureType);
    public String getFeatureName();
    public void setFeatureName(String featureName);
    public String getDrillholeLicenceName();
    public void setDrillholeLicenceName(String drillholeLicenceName);
    public Date getStartDate();
    public void setStartDate(Date startDate);
    public Date getFinishDate();
    public void setFinishDate(Date finishDate);
    public String getComments();
    public void setComments(String comments);
    public Double getDatumElevation();
    public void setDatumElevation(Double datumElevation);
    public Double getStartDepth();
    public void setStartDepth(Double startDepth);
    public String getDatumType();
    public void setDatumType(String datumType);
    public Double getFinishDepth();
    public void setFinishDepth(Double finishDepth);
	public String getDepthUnit();
	public void setDepthUnit(String depthUnit);
    public String getStartDateRounding();
    public void setStartDateRounding(String startDateRounding);
    public String getFinishDateRounding();
    public void setFinishDateRounding(String finishDateRounding);
	public FrNumber getFrNumber();
	public void setFrNumber(FrNumber frNumber);
	public FrNumber getYardFrNumber();
	public void setYardFrNumber(FrNumber yardFrNumber);
    public Person getPerson();
    public void setPerson(Person person);
    public Folder getMasterFile();
    public void setMasterFile(Folder masterFile);
    public Audit getAudit();
    public void setAudit(Audit auditTable);
    public SiteView getSiteView();
    public void setSiteView(SiteView siteView);
    public RegistrationArea getRegistrationArea();
    public void setRegistrationArea(RegistrationArea registrationArea);
    public Set<Sample> getSamples();
    public void setSamples(Set<Sample> samples);
    public Set<Folder> getFolders();
    public void setFolders(Set<Folder> folders);
    public Set<Relationship> getRelationships();
    public void setRelationships(Set<Relationship> relationships);
    public Set<MetaCat> getMetaCats();
    public void setMetaCats(Set<MetaCat> metaCats);
}
