CREATE TABLE Adoptor
(
Record_ID	NUMBER(7),
Person_ID	NUMBER(5),
PRIMARY KEY (Record_ID, Person_ID),
CONSTRAINT Adoptor_FK1 FOREIGN KEY (Record_ID) REFERENCES Adoption (Record_ID) ON DELETE CASCADE,
CONSTRAINT Adoptor_FK2 FOREIGN KEY (Person_ID) REFERENCES Person (Person_ID)
);

CREATE INDEX Adoptor_IDX1 ON Adoptor (Record_ID) TABLESPACE Indx;
CREATE INDEX Adoptor_IDX2 ON Adoptor (Person_ID) TABLESPACE Indx;