CREATE TABLE Sent_To
(
Sent_To_ID	NUMBER(7),
Sample_ID	NUMBER(7) NOT NULL,
Fossil_Group_ID	NUMBER(3),
Person_ID	NUMBER(5),
Lab_ID		NUMBER(4),
Comments	VARCHAR2(255),
PRIMARY KEY (Sent_To_ID),
CONSTRAINT Sent_To_FK1 FOREIGN KEY (Sample_ID) REFERENCES Sample (Sample_ID) ON DELETE CASCADE,
CONSTRAINT Sent_To_FK2 FOREIGN KEY (Fossil_Group_ID) REFERENCES Lookup (Lookup_ID),
CONSTRAINT Sent_To_FK3 FOREIGN KEY (Person_ID) REFERENCES Person (Person_ID),
CONSTRAINT Sent_To_FK4 FOREIGN KEY (Lab_ID) REFERENCES SC.Lab (Lab_ID)
);

CREATE INDEX Sent_To_IDX1 ON Sent_To (Sample_ID) TABLESPACE Indx;
CREATE INDEX Sent_To_IDX2 ON Sent_To (Fossil_Group_ID) TABLESPACE Indx;
CREATE INDEX Sent_To_IDX3 ON Sent_To (Person_ID) TABLESPACE Indx;
CREATE INDEX Sent_To_IDX4 ON Sent_To (Lab_ID) TABLESPACE Indx;