# Date and version values inserted into data entry template 
project.version=${project.version}
build.display.date=${timestamp}
# Min version checked against version submitted by data entry templates
minimum.upload.template.version=3.2.5.87

