create schema sc;
create schema fr;
set schema fr;

CREATE SEQUENCE AGE_SEQ START WITH 176;
CREATE SEQUENCE AUDIT_EDIT_SEQ START WITH 285216;
CREATE SEQUENCE AUDIT_SEQ START WITH 438205;
CREATE SEQUENCE CONFIDENTIAL_GROUP_SEQ START WITH 82;
CREATE SEQUENCE FEATURE_SEQ START WITH 118779;
CREATE SEQUENCE FOLDER_SEQ START WITH 13419;
CREATE SEQUENCE FR_SEQ START WITH 165679;
CREATE SEQUENCE FU_SEQ START WITH 2224;
CREATE SEQUENCE LAB_SECTION_SEQ START WITH 102;
CREATE SEQUENCE LOG_SEQ START WITH 287107;
CREATE SEQUENCE PAL_LIST_SEQ START WITH 2811575;
CREATE SEQUENCE PERSON_SEQ START WITH 14801;
CREATE SEQUENCE RECORD_SEQ START WITH 184578;
CREATE SEQUENCE RELATIONSHIP_SEQ START WITH 115494;
CREATE SEQUENCE SAMPLE_SEQ START WITH 183791;
CREATE SEQUENCE SDE_LOGFILE_LID_GEN START WITH 47539;
CREATE SEQUENCE SENT_TO_SEQ START WITH 147515;
CREATE SEQUENCE STAGE_SEQ START WITH 17014;
CREATE SEQUENCE TAXA_SEQ START WITH 42604;

CREATE TABLE ADOPTION ( RECORD_ID NUMBER(8) NOT NULL, ADOPTION_DATE DATE, DATE_ROUNDING VARCHAR2(5), ADOPTED_STAGE_ID NUMBER(8), COMMENTS VARCHAR2(512), PRIMARY KEY (RECORD_ID) );
CREATE TABLE ADOPTOR ( RECORD_ID NUMBER(7) NOT NULL, PERSON_ID NUMBER(5) NOT NULL, PRIMARY KEY (RECORD_ID, PERSON_ID) );
CREATE TABLE AGE ( AGE_ID NUMBER(3) NOT NULL, NAME VARCHAR2(64) NOT NULL, CODE VARCHAR2(16) NOT NULL, PERIOD VARCHAR2(16), BASE_AGE NUMBER(7,3) NOT NULL, TOP_AGE NUMBER(7,3) NOT NULL, OBSOLETE_FLAG NUMBER(1), COMMENTS VARCHAR2(128), DUPLICATE_FLAG NUMBER(1), PRIMARY KEY (AGE_ID) );
CREATE TABLE AUDIT_CONFID ( AUDIT_ID NUMBER(8) NOT NULL, GROUP_ID NUMBER(2) NOT NULL, PRIMARY KEY (AUDIT_ID, GROUP_ID) );
CREATE TABLE AUDIT_EDIT ( AUDIT_EDIT_ID NUMBER(9) NOT NULL, AUDIT_ID NUMBER(8), EDITED_BY_ID NUMBER(7), EDITED_DATE DATE, COMMENTS VARCHAR2(255), PRIMARY KEY (AUDIT_EDIT_ID) );
CREATE TABLE AUDIT_TABLE ( AUDIT_ID NUMBER(8) NOT NULL, STATUS VARCHAR2(16) DEFAULT 'working'  NOT NULL, DATA_ORIGIN_ID NUMBER(4) DEFAULT 908, CREATED_BY_ID NUMBER(7), CREATED_DATE DATE, SUBMITTED_BY_ID NUMBER(7), SUBMITTED_DATE DATE, APPROVED_BY_ID NUMBER(7), APPROVED_DATE DATE, SEND_MESSAGE VARCHAR2(6), WORKING_COMMENTS VARCHAR2(255), WORKING_FOLDER_ID NUMBER(7), CURATOR_COMMENTS VARCHAR2(255), SECURITY_CLASS_ID NUMBER(5) DEFAULT 4, CONFIDENTIAL_FLAG NUMBER(1), CONFID_PERIOD NUMBER(2,1), CONFID_LAPSE_DATE DATE, CONFID_LAPSE_EMAIL VARCHAR2(32), CONFID_EMAIL_FLAG NUMBER(1), DONT_DELETE_FLAG NUMBER(1), PRIMARY KEY (AUDIT_ID) );
CREATE TABLE BAD_RECORDS ( RECORD_ID NUMBER(8) NOT NULL, PRIMARY KEY (RECORD_ID) );
CREATE TABLE BASIS_PAL_LIST ( RECORD_ID NUMBER(7), GROUP_ID NUMBER(3), TAXONOMIC_NAME VARCHAR2(128), PKEY NUMBER(6) NOT NULL, AUTHOR VARCHAR2(64), COMMENTS VARCHAR2(128), TAXA_ID NUMBER(5), PRIMARY KEY (PKEY) );
CREATE TABLE BEDDING ( BEDDING_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (BEDDING_ID), CONSTRAINT SYS_C0030242 UNIQUE (CODE) );
CREATE TABLE BED_THICKNESS ( THICKNESS_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (THICKNESS_ID), CONSTRAINT SYS_C0030240 UNIQUE (CODE) );
CREATE TABLE BEGG_FEATURE ( FEATURE_ID NUMBER(8) NOT NULL, PRIMARY KEY (FEATURE_ID) );
CREATE TABLE BORE_FRED ( FEATURE_ID NUMBER(10) NOT NULL, BH_ID NUMBER(10) NOT NULL, CONSTRAINT BORE_PETLAB_PK PRIMARY KEY (FEATURE_ID, BH_ID) );
COMMENT ON TABLE BORE_FRED IS 'Assignment of a unique bore_hole to a Fossil Record feature';
COMMENT ON COLUMN BORE_FRED.FEATURE_ID IS 'Foreign key to FEATURE table';
COMMENT ON COLUMN BORE_FRED.BH_ID IS 'Foreign key to sc.BORE_HOLE table';
CREATE TABLE CARBONATE ( CARBONATE_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (CARBONATE_ID), CONSTRAINT SYS_C0030244 UNIQUE (CODE) );
CREATE TABLE COLLECTOR ( PERSON_ID NUMBER(5) NOT NULL, SAMPLE_ID NUMBER(7) NOT NULL, PRIMARY KEY (SAMPLE_ID, PERSON_ID) );
CREATE TABLE COLOUR_MODIFIER ( MODIFIER_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (MODIFIER_ID), CONSTRAINT SYS_C0030246 UNIQUE (CODE) );
CREATE TABLE CONFIDENTIAL_GROUP ( GROUP_ID NUMBER(2) NOT NULL, NAME VARCHAR2(32), ORG_ID NUMBER(8), PRIMARY KEY (GROUP_ID) );
CREATE TABLE CONFID_GROUP_OWNERS ( GROUP_ID NUMBER(8) NOT NULL, USER_ID NUMBER(7) NOT NULL, PRIMARY KEY (GROUP_ID, USER_ID) );
CREATE TABLE CONFID_GROUP_USER ( GROUP_ID NUMBER(8) NOT NULL, USER_ID NUMBER(7) NOT NULL, PRIMARY KEY (GROUP_ID, USER_ID) );
CREATE TABLE DATA_ORIGIN ( ORIGIN_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, DESCRIPTION VARCHAR2(255), PRIMARY KEY (ORIGIN_ID) );
CREATE TABLE DEFAULT_IDENTIFICATION_DATE ( PERSON_ID NUMBER(6) NOT NULL, IDENTIFICATION_DATE DATE NOT NULL, PRIMARY KEY (PERSON_ID, IDENTIFICATION_DATE) );
COMMENT ON TABLE DEFAULT_IDENTIFICATION_DATE IS 'Used by squirrel_age_view.';
CREATE TABLE DOUBLE_TAXA ( TAXA_ID NUMBER(6) NOT NULL, TAXONOMIC_NAME VARCHAR2(128), GROUP_ID NUMBER(3), PRIMARY KEY (TAXA_ID) );
CREATE TABLE DRILL_TYPE ( DRILL_TYPE_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, PRIMARY KEY (DRILL_TYPE_ID) );
CREATE TABLE DUPS ( OLD_STAGE_ID VARCHAR2(8), NEW_STAGE_ID VARCHAR2(8), NAME VARCHAR2(30) );
CREATE TABLE FEATURE ( FEATURE_ID NUMBER(7) NOT NULL, SITE_ID NUMBER(7), AUDIT_ID NUMBER(8), MASTERFILE_ID NUMBER(7), FIELD_NUMBER VARCHAR2(32), LOCALITY VARCHAR2(1024), REG_AREA_ID NUMBER(4), COMMENTS VARCHAR2(1024), FEATURE_TYPE VARCHAR2(26) NOT NULL, FEATURE_NAME VARCHAR2(64), DRILLHOLE_LICENCE_NAME VARCHAR2(64), START_DATE DATE, START_DATE_ROUNDING VARCHAR2(5), FINISH_DATE DATE, FINISH_DATE_ROUNDING VARCHAR2(5), PERSON_ID NUMBER(5), DATUM_TYPE VARCHAR2(8), DATUM_ELEVATION NUMBER(6,2), START_DEPTH NUMBER(8,3), FINISH_DEPTH NUMBER(8,3), ORIG_SYSTEM_ID NUMBER(3), ORIG_COORD VARCHAR2(36), MAP_YEAR NUMBER(4), COORD_COMMENTS VARCHAR2(1024), FR_ID NUMBER(7), YARD_FR_ID NUMBER(7), DEPTH_UNIT VARCHAR2(2), PRIMARY KEY (FEATURE_ID) );
CREATE TABLE FEATURE_META ( FEATURE_ID NUMBER(7) NOT NULL, META_ID NUMBER(10) NOT NULL, PRIMARY KEY (FEATURE_ID, META_ID) );
CREATE TABLE FOLDER ( FOLDER_ID NUMBER(7) NOT NULL, NAME VARCHAR2(32) NOT NULL, OWNER_ID NUMBER(5), FOLDER_TYPE NUMBER(1) NOT NULL, PRIMARY KEY (FOLDER_ID) );
CREATE TABLE FOLDER_CONTENT ( FOLDER_ID NUMBER(7) NOT NULL, FEATURE_ID NUMBER(7) NOT NULL, PRIMARY KEY (FOLDER_ID, FEATURE_ID) );
CREATE TABLE FOLDER_RIGHT ( RIGHT_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE NUMBER(3) NOT NULL, PRIMARY KEY (RIGHT_ID), CONSTRAINT SYS_C0030250 UNIQUE (CODE) );
CREATE TABLE FOLDER_TYPE ( FOLDER_TYPE_ID NUMBER(1) NOT NULL, NAME VARCHAR2(32) NOT NULL, PRIMARY KEY (FOLDER_TYPE_ID), CONSTRAINT SYS_C0030268 UNIQUE (NAME) );
CREATE TABLE FOLDER_USER ( FOLDER_ID NUMBER(7), USER_ID NUMBER(5), USER_RIGHTS NUMBER(3) DEFAULT 1, FU_ID NUMBER(5) NOT NULL, PRIMARY KEY (FU_ID) );
CREATE TABLE FOSSIL_GROUP ( GROUP_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, PRIMARY KEY (GROUP_ID) );
CREATE TABLE FR ( FR_ID NUMBER(7) );
CREATE TABLE FR_NUMBER ( FR_ID NUMBER(7) NOT NULL, MAP_SHEET VARCHAR2(7) NOT NULL, SERIAL_NUMBER NUMBER(5) NOT NULL, RECOLLECTION_NUMBER VARCHAR2(2), FRNUM_COMMENTS VARCHAR2(255), FR_NUMBER VARCHAR2(15), OBSOLETE VARCHAR2(1), DELETE_FLAG NUMBER(1), PRIMARY KEY (FR_ID) );
CREATE TABLE FR_USER ( PE_ID NUMBER(7) NOT NULL, LAST_LOGIN DATE, PRIMARY KEY (PE_ID) );
COMMENT ON TABLE FR_USER IS 'Log of  latest login of each user';
CREATE TABLE GRAIN_SIZE ( GRAIN_SIZE_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (GRAIN_SIZE_ID), CONSTRAINT SYS_C0030253 UNIQUE (CODE) );
CREATE TABLE HARDNESS ( HARDNESS_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (HARDNESS_ID), CONSTRAINT SYS_C0030255 UNIQUE (CODE) );
CREATE TABLE IDENTIFIER ( RECORD_ID NUMBER(7) NOT NULL, PERSON_ID NUMBER(5) NOT NULL, PRIMARY KEY (RECORD_ID, PERSON_ID) );
CREATE TABLE JAMES_TEMP ( FR_NUMBER VARCHAR2(16), DEPTH_TO NUMBER(10,3), DEPTH_FROM NUMBER(10,3), SAMPLE_ID NUMBER(8) NOT NULL, PRIMARY KEY (SAMPLE_ID) );
CREATE TABLE JOE ( FR VARCHAR2(36), SAMPLE_ID NUMBER );
CREATE TABLE LAB_SECTION ( LAB_SECTION_ID NUMBER(3) NOT NULL, LAB_ID NUMBER, NAME VARCHAR2(64), CODE VARCHAR2(8), CLOSED VARCHAR2(1), PRIMARY KEY (LAB_SECTION_ID) );
CREATE TABLE LOG_TABLE ( LOG_ID NUMBER(8) NOT NULL, LOG_TYPE VARCHAR2(16), LOG_DATE DATE, USER_ID NUMBER(5), LOCALITY_COUNT NUMBER(5), PRIMARY KEY (LOG_ID) );
CREATE TABLE LOOKUP ( LOOKUP_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8), DESCRIPTION VARCHAR2(255), FIELDNAME VARCHAR2(64), PRIMARY KEY (LOOKUP_ID) );
CREATE TABLE PALEONTOLOGY ( RECORD_ID NUMBER(8) NOT NULL, IDENTIFICATION_DATE DATE, DATE_ROUNDING VARCHAR2(5), STAGE_ID NUMBER(8), STAGE_COMMENTS VARCHAR2(1024), LAB_SECTION_ID NUMBER(4), LAB_NUMBER VARCHAR2(64), COLLECTION_COMMENTS VARCHAR2(1549), PAL_ID NUMBER(8), PRIMARY KEY (RECORD_ID) );
CREATE TABLE PAL_LIST ( PAL_LIST_ID NUMBER(8) NOT NULL, RECORD_ID NUMBER(8), GROUP_ID NUMBER(4), TAXA_ID NUMBER(7), TAXONOMIC_NAME VARCHAR2(128), SPECIMEN_COUNT NUMBER(5), SPECIMEN_COORDS VARCHAR2(255), COMMENTS VARCHAR2(1024), PRIMARY KEY (PAL_LIST_ID) );
CREATE TABLE PAL_LIST_META ( PAL_LIST_ID NUMBER(8) NOT NULL, META_ID NUMBER(10) NOT NULL, PRIMARY KEY (PAL_LIST_ID, META_ID) );
CREATE TABLE PERSON ( PERSON_ID NUMBER(5) NOT NULL, ST_CODE NUMBER(4), NAME VARCHAR2(64) NOT NULL, PRIMARY KEY (PERSON_ID) );
CREATE TABLE RECORD ( RECORD_ID NUMBER(8) NOT NULL, SAMPLE_ID NUMBER(7) NOT NULL, AUDIT_ID NUMBER(8), PAL_LIST_AUDIT_ID NUMBER(8), PRIMARY KEY (RECORD_ID) );
CREATE TABLE RECORD_META ( RECORD_ID NUMBER(8) NOT NULL, META_ID NUMBER(10) NOT NULL, PRIMARY KEY (RECORD_ID, META_ID) );
CREATE TABLE REGISTRATION_AREA ( REG_AREA_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (REG_AREA_ID), CONSTRAINT SYS_C0030257 UNIQUE (CODE) );
CREATE TABLE RELATIONSHIP ( RELATIONSHIP_ID NUMBER(8) NOT NULL, RELATIONSHIP_TYPE VARCHAR2(16) NOT NULL, RELATED_FEATURE_ID NUMBER(7), STRAT_UNIT VARCHAR2(255), DISTANCE NUMBER(8,3), DISTANCE_MOD VARCHAR2(2), RELATION_TYPE_ID NUMBER(4) NOT NULL, DISTANCE_RANGE NUMBER(8,3), SAMPLE_ID NUMBER(7), STRAT_UNIT_ID NUMBER(5), CONSTRAINT RELATIONSHIP_PK PRIMARY KEY (RELATIONSHIP_ID) );
CREATE TABLE RELATIONSHIP_TYPE ( RELTYPE_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, RELATION_TYPE VARCHAR2(16) NOT NULL, PRIMARY KEY (RELTYPE_ID) );
CREATE TABLE RELATION_TYPE ( RELATION_TYPE VARCHAR2(16) NOT NULL, CONSTRAINT PK_RELATION_TYPE PRIMARY KEY (RELATION_TYPE) );
CREATE TABLE ROCK_COLOUR ( COLOUR_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (COLOUR_ID), CONSTRAINT SYS_C0030259 UNIQUE (CODE) );
CREATE TABLE SAMPLE ( SAMPLE_ID NUMBER(7) NOT NULL, FEATURE_ID NUMBER(7) NOT NULL, FR_ID NUMBER(7), TOP_DEPTH NUMBER(8,3), BOTTOM_DEPTH NUMBER(8,3), DRILL_TYPE VARCHAR2(16), COMMENTS VARCHAR2(255), DRILL_TYPE_ID NUMBER(4), YARD_FR_ID NUMBER(7), AUDIT_ID NUMBER(8), COLLECTION_DATE DATE, DATE_ROUNDING VARCHAR2(5), STRAT_UNIT VARCHAR2(255), IN_PLACE VARCHAR2(7), NOT_COLLECTED VARCHAR2(1024), SIGNIFICANCE VARCHAR2(1024), INFERRED_STAGE_ID NUMBER(8), KNOWN_STAGE_ID NUMBER(8), COLUMN_MAP VARCHAR2(255), DIP NUMBER(2), DIP_DIRECTION VARCHAR2(2), STRIKE NUMBER(3), FACING VARCHAR2(10), PRIMARY_GRAINSIZE_ID NUMBER(4), SECONDARY_GRAINSIZE_ID NUMBER(4), COMPARATOR_USED VARCHAR2(1), BED_THICK_ID NUMBER(4), PRIMARY_BEDDING_ID NUMBER(4), SECONDARY_BEDDING_ID NUMBER(4), WEATHERING_ID NUMBER(4), HARDNESS_ID NUMBER(4), CARBONATE_ID NUMBER(4), COLOUR_MODIFIER_ID NUMBER(4), PRIMARY_COLOUR_ID NUMBER(4), SECONDARY_COLOUR_ID NUMBER(4), WET VARCHAR2(3), ROCK_NATURE VARCHAR2(512), DEPOSITION_ENV VARCHAR2(300), CORRESPONDENCE VARCHAR2(512), DEPTH_UNIT VARCHAR2(2), STRAT_COMMENTS VARCHAR2(1600), PRIMARY KEY (SAMPLE_ID) );
CREATE TABLE SAMPLE_META ( SAMPLE_ID NUMBER(7) NOT NULL, META_ID NUMBER(10) NOT NULL, PRIMARY KEY (SAMPLE_ID, META_ID) );
CREATE TABLE SECURITY_CLASS ( CLASS_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, PRIMARY KEY (CLASS_ID) );
CREATE TABLE SEDIMENTARY_FEATURE ( SED_FEATURE_ID NUMBER(4) NOT NULL, ABUNDANT VARCHAR2(1), SAMPLE_ID NUMBER(7) NOT NULL, PRIMARY KEY (SAMPLE_ID, SED_FEATURE_ID) );
CREATE TABLE SEDIMENTARY_FEATURE_TYPE ( SEDFEATURE_TYPE_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (SEDFEATURE_TYPE_ID), CONSTRAINT SYS_C0030263 UNIQUE (CODE) );
CREATE TABLE SENT_TO ( FOSSIL_GROUP_ID NUMBER(3), SENT_DATE DATE, DATE_ROUNDING VARCHAR2(5), PERSON_ID NUMBER(5), LAB_ID NUMBER(4), COMMENTS VARCHAR2(255), SAMPLE_ID NUMBER(7), SENT_TO_ID NUMBER(7) NOT NULL, PRIMARY KEY (SENT_TO_ID) );
CREATE TABLE SIMEDELS ( RECORD_ID NUMBER(6) );
COMMENT ON TABLE SIMEDELS IS 'record ID John sime deleted from tables PALEONTOLOGY, IDENTIFIER AND PAL_LIST on 17Nov08 ca 1500 hours';
CREATE TABLE STAGE ( STAGE_ID NUMBER(8) NOT NULL, STAGE_LOWER_MOD VARCHAR2(1), STAGE_UPPER_MOD VARCHAR2(1), STAGE_MOD VARCHAR2(1), AGE_LOWER_ID NUMBER(3), AGE_UPPER_ID NUMBER(3), BASE_AGE NUMBER(7,3), TOP_AGE NUMBER(7,3), PRIMARY KEY (STAGE_ID) );
CREATE TABLE TAXA_PANEL ( GROUP_ID NUMBER(4) NOT NULL, PANELIST_ID NUMBER(7) NOT NULL, PRIMARY KEY (GROUP_ID, PANELIST_ID) );
CREATE TABLE TAXONOMIC_GROUP ( GROUP_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, PRIMARY KEY (GROUP_ID) );
CREATE TABLE TAXONOMIC_LOOKUP ( TAXA_ID NUMBER(7) NOT NULL, GROUP_ID NUMBER(4) NOT NULL, TAXONOMIC_NAME VARCHAR2(64), AUTHOR VARCHAR2(64), STATUS VARCHAR2(11) NOT NULL, SUBMITTED_BY_ID NUMBER(7), SUBMITTED_DATE DATE, APPROVED_BY_ID NUMBER(7), APPROVED_DATE DATE, SEND_MESSAGE VARCHAR2(1), PANELIST_COMMENTS VARCHAR2(255), PRIMARY KEY (TAXA_ID), CONSTRAINT TAXA_UNQ UNIQUE (GROUP_ID, TAXONOMIC_NAME) );
CREATE TABLE TAXONOMIC_SYNONYM ( TAXA_ID NUMBER(7) NOT NULL, SYNONYM_ID NUMBER(7) NOT NULL );
CREATE TABLE TEMP_LOB ( WHATEVER CLOB );
CREATE TABLE TEMP_YARD_REFS ( FEATURE_ID NUMBER(8) NOT NULL, SHEET VARCHAR2(4), EASTING NUMBER(5,1), NORTHING NUMBER(5,1), COMMENTS VARCHAR2(255), PRIMARY KEY (FEATURE_ID) );
CREATE TABLE USER_LIST ( ID NUMBER(5) NOT NULL, SAMPLEID NUMBER(6), PRIMARY KEY (ID) );
CREATE TABLE WEATHERING ( WEATHERING_ID NUMBER(4) NOT NULL, NAME VARCHAR2(32) NOT NULL, CODE VARCHAR2(8) NOT NULL, PRIMARY KEY (WEATHERING_ID), CONSTRAINT SYS_C0030266 UNIQUE (CODE) );
ALTER TABLE ADOPTION ADD CONSTRAINT ADOPTION_FK1 FOREIGN KEY (RECORD_ID) REFERENCES RECORD (RECORD_ID) ON DELETE CASCADE;
ALTER TABLE ADOPTION ADD CONSTRAINT ADOPTION_FK3 FOREIGN KEY (ADOPTED_STAGE_ID) REFERENCES STAGE (STAGE_ID);
ALTER TABLE ADOPTION ADD CHECK (Date_Rounding IN ('Year', 'Month'));
ALTER TABLE ADOPTOR ADD CONSTRAINT ADOPTOR_FK1 FOREIGN KEY (RECORD_ID) REFERENCES ADOPTION (RECORD_ID) ON DELETE CASCADE;
ALTER TABLE ADOPTOR ADD CONSTRAINT ADOPTOR_FK2 FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID);
ALTER TABLE AUDIT_CONFID ADD CONSTRAINT AUDIT_CONFID_FK1 FOREIGN KEY (AUDIT_ID) REFERENCES AUDIT_TABLE (AUDIT_ID) ON DELETE CASCADE;
ALTER TABLE AUDIT_CONFID ADD CONSTRAINT AUDIT_CONFID_FK2 FOREIGN KEY (GROUP_ID) REFERENCES CONFIDENTIAL_GROUP (GROUP_ID);
ALTER TABLE AUDIT_EDIT ADD CONSTRAINT AUDIT_EDIT_FK1 FOREIGN KEY (AUDIT_ID) REFERENCES AUDIT_TABLE (AUDIT_ID) ON DELETE CASCADE;
ALTER TABLE AUDIT_TABLE ADD CONSTRAINT AUDIT_TABLE_FK6 FOREIGN KEY (WORKING_FOLDER_ID) REFERENCES FOLDER (FOLDER_ID);
ALTER TABLE AUDIT_TABLE ADD CONSTRAINT FK_AUDIT_DATA_ORIGIN FOREIGN KEY (DATA_ORIGIN_ID) REFERENCES DATA_ORIGIN (ORIGIN_ID);
ALTER TABLE AUDIT_TABLE ADD CHECK (Status IN ('working', 'waiting', 'approved', 'rejected'));
ALTER TABLE BORE_FRED ADD CONSTRAINT FEATURE_PK FOREIGN KEY (FEATURE_ID) REFERENCES FEATURE (FEATURE_ID);
ALTER TABLE BORE_FRED ADD CONSTRAINT BORE_FRED_FEATURE_ID_REQ CHECK ("FEATURE_ID" IS NOT NULL);
ALTER TABLE BORE_FRED ADD CONSTRAINT BH_ID_REQ CHECK ("BH_ID" IS NOT NULL);
ALTER TABLE COLLECTOR ADD CONSTRAINT COLLECTOR_FK2 FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID);
ALTER TABLE COLLECTOR ADD CONSTRAINT COLLECTOR_FK1 FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (SAMPLE_ID) ON DELETE CASCADE;
ALTER TABLE CONFID_GROUP_OWNERS ADD CONSTRAINT FK_CONFID_GROUP_OWNERS_GROUP FOREIGN KEY (GROUP_ID) REFERENCES CONFIDENTIAL_GROUP (GROUP_ID);
ALTER TABLE CONFID_GROUP_USER ADD CONSTRAINT CONFID_GROUP_USER_FK1 FOREIGN KEY (GROUP_ID) REFERENCES CONFIDENTIAL_GROUP (GROUP_ID);
ALTER TABLE FEATURE ADD CONSTRAINT FEATURE_FK2 FOREIGN KEY (AUDIT_ID) REFERENCES AUDIT_TABLE (AUDIT_ID);
ALTER TABLE FEATURE ADD CONSTRAINT FEATURE_FK3 FOREIGN KEY (MASTERFILE_ID) REFERENCES FOLDER (FOLDER_ID);
ALTER TABLE FEATURE ADD CONSTRAINT FEATURE_FK7 FOREIGN KEY (FR_ID) REFERENCES FR_NUMBER (FR_ID);
ALTER TABLE FEATURE ADD CONSTRAINT FEATURE_FK8 FOREIGN KEY (YARD_FR_ID) REFERENCES FR_NUMBER (FR_ID);
ALTER TABLE FEATURE ADD CONSTRAINT FEATURE_FK5 FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID);
ALTER TABLE FEATURE ADD CONSTRAINT FK_FEATURE_REG_AREA FOREIGN KEY (REG_AREA_ID) REFERENCES REGISTRATION_AREA (REG_AREA_ID);
ALTER TABLE FEATURE ADD CONSTRAINT FEATURE_DATUM_CHK CHECK (Datum_Type IN ('RT', 'KB', 'Seafloor', 'Top' ,'Bottom'));
ALTER TABLE FEATURE ADD CHECK (Feature_Type IN ('Outcrop', 'Drillhole', 'Vertical Section'));
ALTER TABLE FEATURE ADD CHECK (Start_Date_Rounding IN ('Year', 'Month'));
ALTER TABLE FEATURE ADD CHECK (Finish_Date_Rounding IN ('Year', 'Month'));
ALTER TABLE FEATURE_META ADD CONSTRAINT FEATURE_META_RECORD_FK FOREIGN KEY (FEATURE_ID) REFERENCES FEATURE (FEATURE_ID) ON DELETE CASCADE;
ALTER TABLE FOLDER ADD CONSTRAINT FK_FOLDER_TYPE FOREIGN KEY (FOLDER_TYPE) REFERENCES FOLDER_TYPE (FOLDER_TYPE_ID);
ALTER TABLE FOLDER_CONTENT ADD CONSTRAINT FOLDER_CONTENT_FK2 FOREIGN KEY (FEATURE_ID) REFERENCES FEATURE (FEATURE_ID) ON DELETE CASCADE;
ALTER TABLE FOLDER_CONTENT ADD CONSTRAINT FOLDER_CONTENT_FK1 FOREIGN KEY (FOLDER_ID) REFERENCES FOLDER (FOLDER_ID);
ALTER TABLE FOLDER_USER ADD CONSTRAINT FOLDER_USER_FK1 FOREIGN KEY (FOLDER_ID) REFERENCES FOLDER (FOLDER_ID) ON DELETE CASCADE;
ALTER TABLE IDENTIFIER ADD CONSTRAINT IDENTIFIER_FK1 FOREIGN KEY (RECORD_ID) REFERENCES PALEONTOLOGY (RECORD_ID) ON DELETE CASCADE;
ALTER TABLE IDENTIFIER ADD CONSTRAINT IDENTIFIER_FK2 FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID);
ALTER TABLE PALEONTOLOGY ADD CONSTRAINT PALEONTOLOGY_FK4 FOREIGN KEY (LAB_SECTION_ID) REFERENCES LAB_SECTION (LAB_SECTION_ID);
ALTER TABLE PALEONTOLOGY ADD CONSTRAINT PALEONTOLOGY_FK1 FOREIGN KEY (RECORD_ID) REFERENCES RECORD (RECORD_ID) ON DELETE CASCADE;
ALTER TABLE PALEONTOLOGY ADD CONSTRAINT PALEONTOLOGY_FK3 FOREIGN KEY (STAGE_ID) REFERENCES STAGE (STAGE_ID);
ALTER TABLE PALEONTOLOGY ADD CHECK (Date_Rounding IN ('Year', 'Month'));
ALTER TABLE PAL_LIST ADD CONSTRAINT PAL_LIST_FK1 FOREIGN KEY (RECORD_ID) REFERENCES PALEONTOLOGY (RECORD_ID) ON DELETE CASCADE;
ALTER TABLE PAL_LIST ADD CONSTRAINT PAL_LIST_FK3 FOREIGN KEY (TAXA_ID) REFERENCES TAXONOMIC_LOOKUP (TAXA_ID);
ALTER TABLE PAL_LIST ADD CONSTRAINT FK_PAL_LIST_GROUP FOREIGN KEY (GROUP_ID) REFERENCES TAXONOMIC_GROUP (GROUP_ID);
ALTER TABLE PAL_LIST_META ADD CONSTRAINT PAL_LIST_META_RECORD_FK FOREIGN KEY (PAL_LIST_ID) REFERENCES PAL_LIST (PAL_LIST_ID) ON DELETE CASCADE;
ALTER TABLE RECORD ADD CONSTRAINT RECORD_FK2 FOREIGN KEY (AUDIT_ID) REFERENCES AUDIT_TABLE (AUDIT_ID);
ALTER TABLE RECORD ADD CONSTRAINT RECORD_FK3 FOREIGN KEY (PAL_LIST_AUDIT_ID) REFERENCES AUDIT_TABLE (AUDIT_ID);
ALTER TABLE RECORD ADD CONSTRAINT RECORD_FK1 FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (SAMPLE_ID) ON DELETE CASCADE;
ALTER TABLE RECORD_META ADD CONSTRAINT RECORD_META_RECORD_FK FOREIGN KEY (RECORD_ID) REFERENCES RECORD (RECORD_ID) ON DELETE CASCADE;
ALTER TABLE RELATIONSHIP ADD CONSTRAINT RELATIONSHIP_FK2 FOREIGN KEY (RELATED_FEATURE_ID) REFERENCES FEATURE (FEATURE_ID);
ALTER TABLE RELATIONSHIP ADD CONSTRAINT FK_RELATIONSHIP_RELTYPE FOREIGN KEY (RELATION_TYPE_ID) REFERENCES RELATIONSHIP_TYPE (RELTYPE_ID);
ALTER TABLE RELATIONSHIP ADD CONSTRAINT FK_RELATION_TYPE FOREIGN KEY (RELATIONSHIP_TYPE) REFERENCES RELATION_TYPE (RELATION_TYPE);
ALTER TABLE RELATIONSHIP ADD CONSTRAINT RELATIONSHIP_FK1 FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (SAMPLE_ID) ON DELETE CASCADE;
ALTER TABLE RELATIONSHIP ADD CONSTRAINT RELATIONSHIP_CK1 CHECK (Related_Feature_ID IS NOT NULL OR Strat_Unit IS NOT NULL);
ALTER TABLE RELATIONSHIP ADD CONSTRAINT RELATIONSHIP_CK161095890514984 CHECK (Distance_Mod IN ('c.', '?'));
ALTER TABLE SAMPLE ADD CONSTRAINT SAMPLE_FK5 FOREIGN KEY (AUDIT_ID) REFERENCES AUDIT_TABLE (AUDIT_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT SAMPLE_FK1 FOREIGN KEY (FEATURE_ID) REFERENCES FEATURE (FEATURE_ID) ON DELETE CASCADE;
ALTER TABLE SAMPLE ADD CONSTRAINT SAMPLE_FK2 FOREIGN KEY (FR_ID) REFERENCES FR_NUMBER (FR_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT SAMPLE_FK3 FOREIGN KEY (YARD_FR_ID) REFERENCES FR_NUMBER (FR_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT SAMPLE_FK6 FOREIGN KEY (INFERRED_STAGE_ID) REFERENCES STAGE (STAGE_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT SAMPLE_FK7 FOREIGN KEY (KNOWN_STAGE_ID) REFERENCES STAGE (STAGE_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_BED_THICK FOREIGN KEY (BED_THICK_ID) REFERENCES BED_THICKNESS (THICKNESS_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_PRIMARY_BEDDING FOREIGN KEY (PRIMARY_BEDDING_ID) REFERENCES BEDDING (BEDDING_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_SECONDARY_BEDDING FOREIGN KEY (SECONDARY_BEDDING_ID) REFERENCES BEDDING (BEDDING_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_CARBONATE FOREIGN KEY (CARBONATE_ID) REFERENCES CARBONATE (CARBONATE_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_COLOUR_MOD FOREIGN KEY (COLOUR_MODIFIER_ID) REFERENCES COLOUR_MODIFIER (MODIFIER_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_DRILL_TYPE FOREIGN KEY (DRILL_TYPE_ID) REFERENCES DRILL_TYPE (DRILL_TYPE_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_PRI_GRAIN_SIZE FOREIGN KEY (PRIMARY_GRAINSIZE_ID) REFERENCES GRAIN_SIZE (GRAIN_SIZE_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_SEC_GRAIN_SIZE FOREIGN KEY (SECONDARY_GRAINSIZE_ID) REFERENCES GRAIN_SIZE (GRAIN_SIZE_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_HARDNESS FOREIGN KEY (HARDNESS_ID) REFERENCES HARDNESS (HARDNESS_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_PRI_COLOUR FOREIGN KEY (PRIMARY_COLOUR_ID) REFERENCES ROCK_COLOUR (COLOUR_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_SEC_COLOUR FOREIGN KEY (SECONDARY_COLOUR_ID) REFERENCES ROCK_COLOUR (COLOUR_ID);
ALTER TABLE SAMPLE ADD CONSTRAINT FK_SAMPLE_WEATHERING FOREIGN KEY (WEATHERING_ID) REFERENCES WEATHERING (WEATHERING_ID);
ALTER TABLE SAMPLE ADD CHECK (Date_Rounding IN ('Year', 'Month'));
ALTER TABLE SAMPLE ADD CHECK (In_Place IN ('Yes', 'No', 'Almost', 'Unknown'));
ALTER TABLE SAMPLE ADD CHECK (Dip <= 90);
ALTER TABLE SAMPLE ADD CHECK (Dip_Direction IN ('N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'));
ALTER TABLE SAMPLE ADD CHECK (Strike <= 360);
ALTER TABLE SAMPLE ADD CHECK (Facing IN ('Normal', 'Overturned'));
ALTER TABLE SAMPLE ADD CHECK (Comparator_Used IN ('Y', 'N'));
ALTER TABLE SAMPLE ADD CHECK (Wet IN ('Wet', 'Dry'));
ALTER TABLE SAMPLE ADD CHECK (Depth_Unit IN ('m', 'ft'));
ALTER TABLE SAMPLE_META ADD CONSTRAINT SAMPLE_META_RECORD_FK FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (SAMPLE_ID);
ALTER TABLE SEDIMENTARY_FEATURE ADD CONSTRAINT FK_SED_FEATURE_TYPE FOREIGN KEY (SED_FEATURE_ID) REFERENCES SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID);
ALTER TABLE SEDIMENTARY_FEATURE ADD CONSTRAINT SEDIMENTARY_FEATURE_FK1 FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (SAMPLE_ID) ON DELETE CASCADE;
ALTER TABLE SEDIMENTARY_FEATURE ADD CONSTRAINT SEDIMENTARY_FEATURE_CHK1 CHECK (Abundant IN ('Y', 'N'));
ALTER TABLE SENT_TO ADD CONSTRAINT SENT_TO_FK3 FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID);
ALTER TABLE SENT_TO ADD CONSTRAINT FK_SENT_TO_GROUP FOREIGN KEY (FOSSIL_GROUP_ID) REFERENCES FOSSIL_GROUP (GROUP_ID);
ALTER TABLE SENT_TO ADD CONSTRAINT SENT_TO_FK1 FOREIGN KEY (SAMPLE_ID) REFERENCES SAMPLE (SAMPLE_ID) ON DELETE CASCADE;
ALTER TABLE SENT_TO ADD CHECK (Date_Rounding IN ('Year', 'Month'));
ALTER TABLE STAGE ADD CONSTRAINT STAGE_FK3 FOREIGN KEY (AGE_LOWER_ID) REFERENCES AGE (AGE_ID);
ALTER TABLE STAGE ADD CONSTRAINT STAGE_FK4 FOREIGN KEY (AGE_UPPER_ID) REFERENCES AGE (AGE_ID);
ALTER TABLE STAGE ADD CHECK (Stage_Lower_Mod = '?');
ALTER TABLE STAGE ADD CHECK (Stage_Upper_Mod = '?');
ALTER TABLE TAXA_PANEL ADD CONSTRAINT FK_TAXA_PANEL_GROUP FOREIGN KEY (GROUP_ID) REFERENCES TAXONOMIC_GROUP (GROUP_ID);
ALTER TABLE TAXONOMIC_LOOKUP ADD CONSTRAINT FK_TAXONOMIC_LKP_GROUP FOREIGN KEY (GROUP_ID) REFERENCES TAXONOMIC_GROUP (GROUP_ID);
ALTER TABLE TAXONOMIC_SYNONYM ADD CONSTRAINT TAXONOMIC_SYNONYM_FK2 FOREIGN KEY (TAXA_ID) REFERENCES TAXONOMIC_LOOKUP (TAXA_ID);
ALTER TABLE TAXONOMIC_SYNONYM ADD CONSTRAINT TAXONOMIC_SYNONYM_FK3 FOREIGN KEY (SYNONYM_ID) REFERENCES TAXONOMIC_LOOKUP (TAXA_ID);

CREATE TABLE SC.SITE
    (
        SITE_ID NUMBER(7) DEFAULT 0 NOT NULL,
        SITE_NAME VARCHAR2(64),
        LATITUDE FLOAT(126) NOT NULL,
        LONGITUDE FLOAT(126) NOT NULL,
        METHOD_ID NUMBER(3),
        ACCURACY FLOAT(126),
        DIRECTIONS VARCHAR2(1000),
        ORIG_SYSTEM_ID NUMBER(3),
        ORIG_COORD VARCHAR2(100),
        HEIGHT FLOAT(126),
        H_METHOD_ID NUMBER(3),
        H_ACCURACY FLOAT(126),
        COUNTRY_CODE VARCHAR2(2),
        OBJECTID INTEGER NOT NULL,
        OWNER_ID NUMBER(7),
        FLAG NUMBER(2),
        SHAPE varchar2(4000),
    );

CREATE VIEW FR.SITE_VIEW ( FEATURE_ID, FR_NUMBER, FEATURE_TYPE, LOCALITY, SHAPE, OBJECTID ) AS SELECT DISTINCT
f.Feature_ID, FR_Number, Feature_Type, Locality, Shape, s.ObjectID
FROM FEATURE f
  inner join sc.site s
    on f.site_id = s.site_id
  left join FR_NUMBER fr
    on f.fr_id = fr.fr_id
 ;

 CREATE TABLE SC.LAB ( LAB_ID NUMBER(4) NOT NULL, LAB_NAME VARCHAR2(50) NOT NULL, LAB_ADDRESS VARCHAR2(255), LAB_COUNTRY VARCHAR2(2), CONSTRAINT LAB_PK PRIMARY KEY (LAB_ID) );

CREATE VIEW FR_USER_VIEW ( PE_ID, GIVEN_NAME, FAMILY_NAME, FULL_NAME, PE_CLIENT_CODE, CL_COMPANY_NAME, DELETED, FR_WEBSITE_ACCESS, FR_DATA_ENTRY, FR_ADMIN, LAST_LOGIN, USERNAME ) AS select
   1
   , 'Test'
   , 'User'
   , 'Test User'
   , 1
   , 'GNS'
   , 0
   , 1
   , 1
   , 1
   , sysdate
   , 'testuser';

create schema mis;
create view mis.org (CL_CLIENT_CODE,
                        CL_COMPANY_NAME,
                        CL_DELETED)
as select 1, 'GNS', 0;

create schema IP;
CREATE VIEW IP.PERSON_VIEW2
    (
        PE_ID,
        GIVEN_NAME,
        FAMILY_NAME,
        FULL_NAME,
        DELETED,
        PE_CLIENT_CODE,
        PE_OS_LOGIN,
        CL_COMPANY_NAME,
        EMAIL_ADDRESS
    ) AS
    select 1, 'Test', 'User', 'Test User', 0, 1, 'testuser', 'GNS', 'developer@gns.cri.nz';

CREATE VIEW SC.SITE_VIEW
    (
        SITE_ID,
        SITE_NAME,
        LATITUDE,
        LONGITUDE,
        COUNTRY_CODE,
        COUNTRY_NAME,
        NZMG_SHEET,
        NZMG_EAST,
        NZMG_NORTH,
        QMAP_SHEET,
        NZMS262_SHEET,
        NZTOPO50_SHEET,
        DSIRQM_SHEET,
        ISLAND,
        METHOD_ID,
        METHOD,
        ACCURACY,
        DIRECTIONS,
        ORIG_SYSTEM_ID,
        COORD_SYSTEM,
        ORIG_COORD,
        HEIGHT,
        H_METHOD_ID,
        H_METHOD,
        H_ACCURACY,
        OWNER_ID,
        OWNER
    ) AS
SELECT 379265,
    'RQ-3',
    -41.06519000193306, 176.08813195524672,
    'NZ',
    'NZ',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    72,
    null,
    'BP36|595|496',
    null,
    null,
    null,
    null,
    1,
    null;
