create schema sc;

CREATE TABLE SC.LAB ( LAB_ID NUMBER(4) NOT NULL, LAB_NAME VARCHAR2(50) NOT NULL, LAB_ADDRESS VARCHAR2(255), LAB_COUNTRY VARCHAR2(2), CONSTRAINT LAB_PK PRIMARY KEY (LAB_ID) );
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (1, 'Rafter laboratory', 'Gracefield Road, Lower Hutt', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (2, 'Service Laboratories', 'Nelson', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (3, 'Anatech', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (4, 'Lime & Marble Ltd', 'Port Mapua, Nelson', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (5, 'McIntyre Mines NZ Ltd', 'Laboratory Division', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (6, 'Cawthron Institute', 'Nelson', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (8, 'T. Sprott & Associates', 'Auckland', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (9, 'Rocklabs', 'Auckland', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (11, 'Comlabs', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (12, 'W. Graysons & Associates', 'Auckland', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (13, 'Geochemical & Mineralogical', 'Sydney', 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (14, 'PB Minerals Ltd.', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (15, 'TGDL', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (16, 'Amoco', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (17, 'Rapley Wilkinson Labs', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (18, 'Analabs', 'Auckland', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (19, 'Bondar-Clegg', '5420 Canoteek Rd, Ottawa, Ontario, KIJ 8X5', 'CA');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (0, 'unknown', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (250, 'Victoria U', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (251, 'Spectrachem', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (252, 'Otago U', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (253, 'San Diego SU', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (254, 'UCSB', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (255, 'Brown U', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (256, 'GNS', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (257, 'UC Berkeley', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (258, 'Dominion Lab', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (259, 'Geophysics Div', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (260, 'WSU', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (261, 'La Trobe U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (262, 'Macquarie U', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (263, 'Grenoble', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (264, 'New Mex Tech', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (265, 'Other', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (266, 'Auckland U', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (267, 'Canterbury U', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (268, 'INS', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (269, 'NZGS', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (270, 'AAEC', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (271, 'ANU', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (272, 'Caltech', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (273, 'U Sydney', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (274, 'Curtin University', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (275, 'FSU', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (276, 'HRI', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (277, 'Yale U', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (278, 'Institute fur Mineralogie', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (279, 'Lucas Heights NSW', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (280, 'MIT', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (281, 'UNSW', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (282, 'Okayama University of Science', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (283, 'UBC', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (284, 'U Toronto', null, 'CA');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (285, 'USGS', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (286, 'Waikato U', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (287, 'Wollongong University NSW', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (288, 'U Nevada Reno', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (289, 'CSIRO', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (290, 'AGSO', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (20, 'Core', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (335, 'Yamageta University', null, 'JP');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (308, 'Massey U', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (309, 'Lincoln U', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (310, 'UCLA', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (311, 'USC', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (312, 'U Alaska', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (313, 'U Cape Town', null, 'ZA');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (314, 'U Queensland', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (315, 'UWA', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (316, 'Open University', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (317, 'BGS', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (318, 'Geol Surv Canada', null, 'CA');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (319, 'Stanford', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (320, 'U Mass', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (321, 'U Glasgow SURRC', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (322, 'U Mainz', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (323, 'U Gottingen', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (324, 'U Tasmania', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (325, 'Adelaide U', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (326, 'Memorial U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (327, 'Smithsonian', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (328, 'Oregon State', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (329, 'U Oregon', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (330, 'UC Santa Cruz', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (331, 'U London', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (332, 'UCSD', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (333, 'Geol Surv Japan', null, 'JP');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (336, 'Analytical Services (WA) Ltd', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (334, 'Halliburton Energy Services', 'Duncan, Oklahoma', 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (337, 'AMDEL', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (338, 'Dartmouth College', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (339, 'ETH', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (340, 'GFZ Potsdam', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (341, 'U Melbourne', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (342, 'Bequerel Labs', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (343, 'St Paul U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (344, 'NIST', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (345, 'U Waterloo', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (346, 'Kanazawa U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (347, 'WWU', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (348, 'Geneva U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (349, 'U Wyoming', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (350, 'Queens U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (351, 'U Nebraska', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (352, 'Mobil', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (353, 'Dartmouth', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (354, 'Geol Surv Denmark', null, 'DK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (355, 'Stratigraphic Solutions Ltd', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (356, 'DSIR', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (357, 'Durham U', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (358, 'Michigan U', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (359, 'DTM', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (360, 'Harvard U', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (361, 'Edinburgh U', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (362, 'Kiel U', null, 'DE');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (363, 'BRGM', null, 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (364, 'U Brest Orleans', null, 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (365, 'U Paris', null, 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (366, 'Montpelier', null, 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (367, 'U Washington', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (368, 'Hong Kong U', null, 'HK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (369, 'U Muenster', null, 'DE');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (370, 'Russian Acad Sci', null, 'RU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (371, 'U Montreal', null, 'CA');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (372, 'U Rhode Island', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (373, 'WWU', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (374, 'Woods Hole', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (375, 'Scripps', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (376, 'Lamont', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (377, 'U Hamburg', null, 'DE');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (378, 'U Frankfurt', null, 'DE');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (379, 'Cambridge U', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (380, 'Oxford U', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (381, 'Max Planck Institute', null, 'DE');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (382, 'U Copenhagen', null, 'DK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (383, 'Purdue U', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (384, 'Monash U', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (385, 'NIGL', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (7, 'Nagoya U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (10, 'Western Washington State U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (21, 'U Nevada Las Vegas', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (22, 'Keele U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (23, 'Open U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (24, 'NERC Isotope Geosciences Laboratory', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (25, 'SUNY', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (26, 'ANSTO', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (27, 'NAA', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (386, 'British Museum of Natural History', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (387, 'Canterbury Museum', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (388, 'Denver Museum', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (389, 'James Cook U', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (390, 'Ehime U', null, 'JP');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (391, 'Geological Institute', 'Moscow', 'RU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (392, 'Geological Survey of Queensland', 'Brisbane', 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (393, 'U Utrecht', null, 'NL');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (394, 'Lund U', null, 'SE');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (395, 'Miyazaki U', null, 'JP');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (396, 'Museum of NZ', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (397, 'Natural History Museum', 'London', 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (398, 'Nevis Associates Ltd', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (399, 'Otago Museum', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (400, 'Sweedish Museum of Natural History', null, 'SE');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (401, 'US National Museum', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (402, 'Utsunomiya U', null, 'JP');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (403, 'Wanganui Museum', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (404, 'Woodside Petroleum', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (405, 'Yokohama National U', null, 'JP');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (406, 'Cardiff U', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (407, 'Hawkes Bay Museum', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (408, 'Western Australian Museum', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (28, 'BGR Hannover', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (409, 'Waikato Museum', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (29, 'Yamaguchi U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (410, 'Auckland Museum', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (30, 'National Taiwan U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (413, 'NZ Historic Places Trust', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (412, 'P and E', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (31, 'UNE Armidale', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (32, 'ALS Chemex', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (414, 'Genalysis Laboratory Services', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (415, 'ISL', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (33, 'U Pisa', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (34, 'ORSTOM', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (35, 'New Mexico Geochronological Laboratory', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (36, 'New Mexico Tech', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (37, 'U Bonn', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (38, 'XRAL, Ontario', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (39, 'Cal State U LA', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (416, 'Australian Laboratory Services Pty Ltd', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (417, 'Carpentaria Exploration Company Mineral Sands Lab', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (418, 'SPROTTS', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (40, 'A to Z Inc', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (41, 'Syracuse U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (42, 'Chemistry Division', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (43, 'Joides Resolution', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (44, 'Ferrara U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (45, 'Tohuku U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (46, 'Leeds U', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (47, 'CRPG Nancy', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (48, 'U Bretagne Occidentale', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (419, 'Zinc Corporation', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (420, 'Geomin', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (421, 'McPhar Geophysics', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (422, 'Nuclear Activation Services Limited', '1280 Main Street West, Hamilton, Ontario', 'CA');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (423, 'U Arizona', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (424, 'UNC-CH', null, 'CH');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (425, 'Graysons Laboratories', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (426, 'Multilabs - Perth', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (427, 'SGS', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (428, 'INAA', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (429, 'Bondar-Clegg', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (430, 'Nuclear Activation Services', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (431, 'ALS Tauranga', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (432, 'ALS Brisbane', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (433, 'Vancouver Petrographics', null, 'CA');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (453, 'Spectrometry Services Ltd.', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (454, 'U Ballarat', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (455, 'U Southampton', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (473, 'Resource Development Laboratories', 'WA', 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (493, 'Geo Labs Sudbury', 'Ontario', 'CA');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (513, 'Fukushima U', 'Fukushima', 'JP');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (533, 'Kyoto U', null, 'JP');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (534, 'Arizona LaserChron', 'University of Arizona', 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (535, 'MOW Dunedin', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (536, 'British Petroleum', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (553, 'Donelick Analytical Inc', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (573, 'St Etienne University', null, 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (574, 'Clermont-Ferrand', null, 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (575, 'Service d''Analyse des Roches et Mineraux', null, 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (593, 'GEOMAR', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (594, 'Activation Laboratories', null, null);
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (613, 'Geotechnics Ltd', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (633, 'SNPA', 'Direction Exploration and Production Centre de Recherches - PAU Group GEOLOGIE', 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (653, 'Analabs Perth', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (674, 'Analabs', 'Suva', 'FJ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (673, 'Analabs', 'Suva', 'FJ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (693, 'U Wales', 'Aberystwyth', 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (713, 'Core Laboratories', 'New Plymouth', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (733, 'Amdel Macraes Flat', 'East Otago', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (734, 'Ultra Trace Labs', 'Perth', 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (753, 'U Alabama', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (773, 'False Laboratory', null, 'AF');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (793, 'Test1', 'Test1', 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (816, 'Institut Francais du Petrole', null, 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (814, 'Baseline Resolution Inc.', 'Texas', 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (815, 'Geotechnical Services Pty Ltd.', 'Perth', 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (817, 'Lanzhou Institute of Geology', null, 'CN');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (818, 'Geo-Optics Ltd', null, 'UK');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (819, 'Keiraville Konsultants', null, 'AU');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (820, 'Newman Energy Research Ltd.', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (821, 'Phillips Petroleum Company', null, 'US');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (822, 'Applied Petroleum Technology', null, 'NO');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (823, 'Coal Research Association of New Zealand Inc.', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (833, 'Sorbonne University', null, 'FR');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (853, 'Bureau Veritas Mineral Laboratories', 'Vancouver', 'CA');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (873, 'Private New Zealand collection', null, 'NZ');
insert into SC.LAB (LAB_ID, LAB_NAME, LAB_ADDRESS, LAB_COUNTRY) values (893, 'McMaster University', null, 'US');

CREATE TABLE SC.ORIG_SYSTEM ( SYSTEM_ID NUMBER(3) NOT NULL, SYSTEM_CODE VARCHAR2(8) NOT NULL, COORD_SYSTEM VARCHAR2(64) NOT NULL, TYPE VARCHAR2(6) NOT NULL, ALLOWED_UNIT VARCHAR2(5), HUMAN_NAME VARCHAR2(100), PRIMARY KEY (SYSTEM_ID) );
COMMENT ON TABLE SC.ORIG_SYSTEM IS 'Original system used prior to conversion to LAT/LONG';
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (1, 'AMUR', 'Amuri Local Circuit Metric', 'Local', 'LM', 'Amuri Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (2, 'AMUR2', 'Amuri 2000 Local Circuit', 'Local2', 'M', 'Amuri 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (3, 'BLUF', 'Bluff Local Circuit Metric', 'Local', 'LM', 'Bluff Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (4, 'BLUF2', 'Bluff 2000 Local Circuit', 'Local2', 'M', 'Bluff 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (5, 'BULL', 'Buller Local circuit Metric', 'Local', 'LM', 'Buller Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (6, 'BULL2', 'Buller 2000 Local Circuit', 'Local2', 'M', 'Buller 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (7, 'CHAT', 'Chatham Island Grid', 'Local', 'LM', 'Chatham Island Grid');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (8, 'COLL', 'Collingwood Local Circuit Metric', 'Local', 'LM', 'Collingwood Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (9, 'COLL2', 'Collingwood 2000 Local Circuit', 'Local2', 'M', 'Collingwood 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (10, 'EDEN', 'Mt Eden Local Circuit Metric', 'Local', 'LM', 'Mt Eden Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (11, 'EDEN2', 'Mt Eden 2000 Local Circuit', 'Local2', 'M', 'Mt Eden 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (12, 'GAWL', 'Gawler Local Circuit Metric', 'Local', 'LM', 'Gawler Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (13, 'GAWL2', 'Gawler 2000 Local Circuit', 'Local2', 'M', 'Gawler 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (14, 'GREY', 'Grey Local Circuit Metric', 'Local', 'LM', 'Grey Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (15, 'GREY2', 'Grey 2000 Local Circuit', 'Local2', 'M', 'Grey 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (16, 'GRMG', 'NZ Map Grid - Trunc.', 'Tmap', 'M', 'NZMS260 map reference (truncated)');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (17, 'MS1S', 'NZMS1 South Island Grid Ref', 'Tmap', 'Y', 'NZMS1 SthIsl (truncated)');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (18, 'HAWK', 'Hawkes Bay Local Circuit Metric', 'Local', 'LM', 'Hawkes Bay Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (19, 'HAWK2', 'Hawkes Bay 2000 Local Circuit', 'Local2', 'M', 'Hawkes Bay 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (20, 'HOKI', 'Hokitika Local Circuit Metric', 'Local', 'LM', 'Hokitika Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (21, 'HOKI2', 'Hokitika 2000 Local Circuit', 'Local2', 'M', 'Hokitika 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (22, 'JACK', 'Jacksons Bay Local Circuit Metric', 'Local', 'LM', 'Jacksons Bay Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (23, 'JACK2', 'Jacksons Bay 2000 Local Circuit', 'Local2', 'M', 'Jacksons Bay 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (24, 'KARA', 'Karamea Local Circuit Metric', 'Local', 'LM', 'Karamea Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (25, 'KARA2', 'Karamea 2000 Local Circuit', 'Local2', 'M', 'Karamea 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (26, 'LIND', 'Lindis Peak Local Circuit Metric', 'Local', 'LM', 'Lindis Peak Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (27, 'LIND2', 'Lindis Peak 2000 Local Circuit', 'Local2', 'M', 'Lindis Peak 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (28, 'LL2K', 'Lat/long GD2000 Datum', 'Geod', 'DC', 'Geographic GD2000');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (29, 'LL49', 'Lat/long GD49 Datum', 'Geod', 'DC', 'Geographic GD49');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (30, 'LLCH', 'Lat/Long Chatham Island Datum', 'Geod', 'DC', 'Geographic Chatham Island Datum');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (31, 'MARL', 'Marlborough Local Circuit Metric', 'Local', 'LM', 'Marlborough Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (32, 'MARL2', 'Marlborough 2000 Local Circuit', 'Local2', 'M', 'Marlborough 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (33, 'NZYS', 'NZ South Island Yard Grid', 'Tmap', 'YLF', 'NZ Yard South Island');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (34, 'NELS', 'Nelson Local Circuit Metric', 'Local', 'LM', 'Nelson Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (35, 'NELS2', 'Nelson 2000 Local Circuit', 'Local2', 'M', 'Nelson 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (36, 'NICH', 'Mount Nicholas Local Circuit Metric', 'Local', 'LM', 'Mount Nicholas Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (37, 'NICH2', 'Mount Nicholas 2000 Local Circuit', 'Local2', 'M', 'Mount Nicholas 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (38, 'NZMG', 'NZ Map Grid - Full', 'Map', 'M', 'New Zealand Map Grid');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (39, 'OBSE', 'Observation Point Local Circuit Metric', 'Local', 'LM', 'Observation Point Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (40, 'OBSE2', 'Observation Point 2000 Local Circuit', 'Local2', 'M', 'Observation Point 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (41, 'OKAR', 'Okarito Local Circuit Metric', 'Local', 'LM', 'Okarito Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (42, 'OKAR2', 'Okarito 2000 Local Circuit', 'Local2', 'M', 'Okarito 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (43, 'OTHR', 'Other - Specify details', 'Unkn', null, 'Other - Specify details');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (44, 'PLEA', 'Mount Pleasant Local Circuit Metric', 'Local', 'LM', 'Mount Pleasant Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (45, 'PLEA2', 'Mount Pleasant 2000 Local Circuit', 'Local2', 'M', 'Mount Pleasant 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (46, 'PLEN', 'Bay of Plenty Local Circuit Metric', 'Local', 'LM', 'Bay of Plenty Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (47, 'PLEN2', 'Bay of Plenty 2000 Local Circuit', 'Local2', 'M', 'Bay of Plenty 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (48, 'POVE', 'Poverty Bay Local Circuit Metric', 'Local', 'LM', 'Poverty Bay Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (49, 'POVE2', 'Poverty Bay 2000 Local Circuit', 'Local2', 'M', 'Poverty Bay 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (50, 'TAIE', 'North Taieri Local Circuit Metric', 'Local', 'LM', 'North Taieri Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (51, 'TAIE2', 'North Taieri 2000 Local Circuit', 'Local2', 'M', 'North Taieri 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (52, 'TARA', 'Taranaki Local Circuit Metric', 'Local', 'LM', 'Taranaki Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (53, 'TARA2', 'Taranaki 2000 Local Circuit', 'Local2', 'M', 'Taranaki 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (54, 'TIMA', 'Timaru Local Circuit Metric', 'Local', 'LM', 'Timaru Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (55, 'TIMA2', 'Timaru 2000 Local Circuit', 'Local2', 'M', 'Timaru 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (56, 'TUHI', 'Tuhirangi Local Circuit Metric', 'Local', 'LM', 'Tuhirangi Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (57, 'TUHI2', 'Tuhirangi 2000 Local Circuit', 'Local2', 'M', 'Tuhirangi 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (58, 'WAIR', 'Wairarapa Local Circuit Metric', 'Local', 'LM', 'Wairarapa Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (59, 'WAIR2', 'Wairarapa 2000 Local Circuit', 'Local2', 'M', 'Wairarapa 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (60, 'WANG', 'Wanganui Local Circuit Metric', 'Local', 'LM', 'Wanganui Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (61, 'WANG2', 'Wanganui 2000 Local Circuit', 'Local2', 'M', 'Wanganui 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (62, 'WELL', 'Wellington Local Circuit Metric', 'Local', 'LM', 'Wellington Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (63, 'WELL2', 'Wellington 2000 Local Circuit', 'Local2', 'M', 'Wellington 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (64, 'YORK', 'Mount York Local Circuit Metric', 'Local', 'LM', 'Mount York Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (65, 'YORK2', 'Mount York 2000 Local Circuit', 'Local2', 'M', 'Mount York 2000 Local Circuit');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (66, 'REMOTE', 'Remote Site', 'Unkn', null, 'Remote Site');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (67, 'AKTM', 'Auckland Island TM', 'Map', 'M', 'Auckland Island Transverse Mercator');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (68, 'CMTM', 'Campbell Island TM', 'Map', 'M', 'Campbell Island Transverse Mercator');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (69, 'MS1N', 'NZMS1 North Island Grid Ref', 'Tmap', 'Y', 'NZMS1 NthIsl (truncated)');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (70, 'NZYN', 'NZ North Island Yard Grid', 'Tmap', 'YLF', 'NZ Yard North Island');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (73, 'LL84', 'Lat/long WGS84 Datum', 'Geod', 'DC', 'Geographic WGS84');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (71, 'NZTM', 'NZ Transverse Mercator', 'Map', 'M', 'New Zealand Transverse Mercator');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (72, 'NZT50', 'NZTopo50', 'Map', 'M', 'NZTopo50 map reference (truncated)');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (74, 'NCTM', 'New Caledonia Transverse Mercator', 'Map', 'M', 'New Caledonia Transverse Mercator');
insert into SC.ORIG_SYSTEM (SYSTEM_ID, SYSTEM_CODE, COORD_SYSTEM, TYPE, ALLOWED_UNIT, HUMAN_NAME) values (76, 'NaD', 'Not A System', 'Unkn', 'DC', 'Not A Datum');

CREATE TABLE SC.METHOD ( METHOD_ID NUMBER(3) NOT NULL, METHOD VARCHAR2(64) NOT NULL, NOM_ACCURACY_XY NUMBER(10,2), NOM_ACCURACY_Z NUMBER(10,2), PRIMARY KEY (METHOD_ID) );
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (1, 'Altimeter', null, 50);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (10, 'Map - >=1:250,000 scale', 500, null);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (11, 'Surveyed', 0.1, 0.5);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (12, 'Verbal description', 1000, null);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (2, 'GPS - Differential', 2, 10);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (3, 'GPS - Field', 10, 10);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (4, 'Location name', 5000, 100);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (5, 'Air Photo', 50, null);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (6, 'Map - <=1:25,000 scale', 10, 20);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (7, 'Map - 1:50,000 scale', 50, 50);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (8, 'Map - scale not specified', 500, 100);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (9, 'Map - 1:100,000 scale', 100, 100);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (13, 'Map sheet known only', 20000, null);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (14, 'Country known only', 2000000, null);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (15, 'Remote site', null, null);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (16, 'Map - 1:63,360 scale', 50, 50);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (17, 'Map - 1:10,000 scale', 10, null);
insert into SC.METHOD (METHOD_ID, METHOD, NOM_ACCURACY_XY, NOM_ACCURACY_Z) values (18, 'Google Elevation', null, 10);



insert into BED_THICKNESS (THICKNESS_ID, NAME, CODE) values (121, 'non-bedded', '1');
insert into BED_THICKNESS (THICKNESS_ID, NAME, CODE) values (122, '> 120 cm', '2');
insert into BED_THICKNESS (THICKNESS_ID, NAME, CODE) values (123, '60 - 120 cm', '3');
insert into BED_THICKNESS (THICKNESS_ID, NAME, CODE) values (124, '5 - 60 cm', '4');
insert into BED_THICKNESS (THICKNESS_ID, NAME, CODE) values (125, '1 - 5 cm', '5');
insert into BED_THICKNESS (THICKNESS_ID, NAME, CODE) values (126, '< 1 cm (laminated)', '6');

insert into BEDDING (BEDDING_ID, NAME, CODE) values (131, 'graded', 'G');
insert into BEDDING (BEDDING_ID, NAME, CODE) values (132, 'slump-folded', 'S');
insert into BEDDING (BEDDING_ID, NAME, CODE) values (133, 'cross-bedded', 'X');

insert into CARBONATE (CARBONATE_ID, NAME, CODE) values (161, 'non-calcareous', '1');
insert into CARBONATE (CARBONATE_ID, NAME, CODE) values (162, 'calcareous', '2');
insert into CARBONATE (CARBONATE_ID, NAME, CODE) values (163, 'limestone', '3');

insert into COLOUR_MODIFIER (MODIFIER_ID, NAME, CODE) values (171, 'light', 'L');
insert into COLOUR_MODIFIER (MODIFIER_ID, NAME, CODE) values (172, 'medium', 'M');
insert into COLOUR_MODIFIER (MODIFIER_ID, NAME, CODE) values (173, 'dark', 'D');

insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (1, 'GNS Science', 8364);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (2, 'Otago University', 7657);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (3, 'Canterbury University', 7636);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (4, 'Victoria University', 8175);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (5, 'Waikato University', 8178);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (6, 'Massey University', 6714);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (7, 'Auckland University', 7631);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (8, 'GNS Paleontologists', null);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (21, 'AU Backlog', null);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (9, 'Chris Clowes', null);
insert into CONFIDENTIAL_GROUP (GROUP_ID, NAME, ORG_ID) values (61, 'GNS', null);

insert into DATA_ORIGIN (ORIGIN_ID, NAME, DESCRIPTION) values (901, 'NZMS1 <1975', 'first version of fossil record form (SIR(GS)4).  Converted to NZMS260');
insert into DATA_ORIGIN (ORIGIN_ID, NAME, DESCRIPTION) values (902, 'NZMS1 1975-1980', 'form GSNZ-F1. Converted to NZMS260');
insert into DATA_ORIGIN (ORIGIN_ID, NAME, DESCRIPTION) values (903, 'NZMS260 <1984', 'form GSNZ-2A');
insert into DATA_ORIGIN (ORIGIN_ID, NAME, DESCRIPTION) values (904, '1984-1991', 'terminal entry on VAX - SQD database');
insert into DATA_ORIGIN (ORIGIN_ID, NAME, DESCRIPTION) values (905, '>1991 terminal', 'terminal entry on VAX - BASIS database');
insert into DATA_ORIGIN (ORIGIN_ID, NAME, DESCRIPTION) values (906, '>1991 foreign', 'foreign data entry -> BASIS');
insert into DATA_ORIGIN (ORIGIN_ID, NAME, DESCRIPTION) values (908, '>=2003', 'Client/server - Oracle database');
insert into DATA_ORIGIN (ORIGIN_ID, NAME, DESCRIPTION) values (907, 'FRF-GR', 'Localities only - captured from paper records');
insert into DATA_ORIGIN (ORIGIN_ID, NAME, DESCRIPTION) values (909, '>=2006 Excel template', 'entry into Oracle database via Excel template');

insert into DRILL_TYPE (DRILL_TYPE_ID, NAME) values (11, 'Cutting');
insert into DRILL_TYPE (DRILL_TYPE_ID, NAME) values (12, 'Core');
insert into DRILL_TYPE (DRILL_TYPE_ID, NAME) values (13, 'Exposure');
insert into DRILL_TYPE (DRILL_TYPE_ID, NAME) values (14, 'Junk Basket');
insert into DRILL_TYPE (DRILL_TYPE_ID, NAME) values (15, 'Sidewall');
insert into DRILL_TYPE (DRILL_TYPE_ID, NAME) values (16, 'Miscell');

insert into FOLDER_RIGHT (RIGHT_ID, NAME, CODE) values (52, 'Edit', 2);
insert into FOLDER_RIGHT (RIGHT_ID, NAME, CODE) values (53, 'Create', 4);
insert into FOLDER_RIGHT (RIGHT_ID, NAME, CODE) values (54, 'Delete', 8);
insert into FOLDER_RIGHT (RIGHT_ID, NAME, CODE) values (55, 'Submit', 16);
insert into FOLDER_RIGHT (RIGHT_ID, NAME, CODE) values (56, 'Admin', 32);
insert into FOLDER_RIGHT (RIGHT_ID, NAME, CODE) values (51, 'Read', 1);
insert into FOLDER_RIGHT (RIGHT_ID, NAME, CODE) values (57, 'Approve', 64);

insert into FOLDER_TYPE (FOLDER_TYPE_ID, NAME) values (1, 'Admin');
insert into FOLDER_TYPE (FOLDER_TYPE_ID, NAME) values (2, 'Personal');
insert into FOLDER_TYPE (FOLDER_TYPE_ID, NAME) values (3, 'Backlog');
insert into FOLDER_TYPE (FOLDER_TYPE_ID, NAME) values (4, 'Backlog Admin');

insert into FOSSIL_GROUP (GROUP_ID, NAME) values (222, 'radiocarbon');
insert into FOSSIL_GROUP (GROUP_ID, NAME) values (223, 'macrofauna');
insert into FOSSIL_GROUP (GROUP_ID, NAME) values (224, 'microfauna');
insert into FOSSIL_GROUP (GROUP_ID, NAME) values (225, 'microflora');
insert into FOSSIL_GROUP (GROUP_ID, NAME) values (227, 'macroflora');
insert into FOSSIL_GROUP (GROUP_ID, NAME) values (226, 'other');

insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (101, 'boulder', 'B');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (102, 'cobble', 'C');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (103, 'pebble', 'P');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (104, 'granule', '1');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (105, 'very coarse sand', '2');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (106, 'coarse sand', '3');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (107, 'medium sand', '4');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (108, 'fine sand', '5');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (109, 'very fine sand', '6');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (110, 'silt', '7');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (111, 'clay', '8');
insert into GRAIN_SIZE (GRAIN_SIZE_ID, NAME, CODE) values (112, 'mud', '9');

insert into HARDNESS (HARDNESS_ID, NAME, CODE) values (151, 'unconsolidated', '1');
insert into HARDNESS (HARDNESS_ID, NAME, CODE) values (152, 'moderately soft', '2');
insert into HARDNESS (HARDNESS_ID, NAME, CODE) values (153, 'moderately hard', '3');
insert into HARDNESS (HARDNESS_ID, NAME, CODE) values (154, 'hard', '4');

insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (1, 339, null, 'AM', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (2, 256, 'Arthropoda', 'AR', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (3, 266, 'Geol. Dept.', 'AU', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (4, 256, 'Plant macrofossils', 'B', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (5, 337, 'Sunbury', 'BPS', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (6, 256, 'Brachiopoda', 'BR', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (7, 256, 'Bryozoa', 'BZ', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (8, 256, 'Chordata', 'CD', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (9, 256, 'Cephalopoda', 'CE', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (10, 256, 'Conodonts', 'CN', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (11, 256, 'Figured Conodonts', 'CNP', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (12, 256, 'Coelenterata, Fossil', 'CO', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (13, 256, 'Diatoms', 'D', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (14, 256, 'Decapod Crustacea', 'DC', 'Y');
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (15, 256, 'Echinodermata', 'EC', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (16, 256, 'Micropaleontology', 'F', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (17, 256, 'Figured Foraminifera', 'FP', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (18, 256, 'Macrofossils', 'GS', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (19, 256, 'Palynology', 'L', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (20, 256, 'Miscellaneous groups', 'MG', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (21, 256, 'Nannoplankton', 'N', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (22, 336, null, 'NM', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (23, 256, 'Modern Mollusca', 'NZRec', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (24, 256, 'Figured Ostracods', 'OP', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (25, 252, 'Geology', 'OU', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (26, 256, 'Protochordata', 'PR', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (27, 256, 'Palynology reference (modern plants)', 'R', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (28, 256, 'Radiolaria', 'RD', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (29, 256, 'Modern Foraminifera', 'RM', 'Y');
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (30, 256, 'Palynology single mounts', 'SM', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (31, 256, 'Palynology stock samples', 'SS', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (32, 256, 'Plant thin section', 'T', 'Y');
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (33, 256, 'Type Conodonts', 'TCN', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (34, 256, 'Type Foraminifera', 'TF', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (35, 256, 'Type Mollusca', 'TM', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (36, 256, 'Type Nannoplankton', 'TN', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (37, 256, 'Type Ostracoda', 'TO', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (38, 267, 'Geol. Dept.', 'UCM', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (39, 250, 'Geol. Dept.', 'V', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (40, 250, 'Geol. Dept. plants', 'VU', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (41, 256, 'Pollen from water', 'W', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (42, 256, 'World Mollusca', 'WM', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (43, 338, 'graptolites', 'zfg', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (44, 338, 'fossil plants', 'zp', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (45, 354, 'Palyonolgy', 'YD', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (61, 355, 'nannofossils', 'SSLC', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (62, 387, 'Aves', 'Av', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (63, 387, 'Mammal', 'Ma', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (64, 396, null, 'S', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (65, 408, null, 'S', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (66, 409, null, 'L', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (67, 410, null, 'AK', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (68, 410, null, 'MA', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (69, 267, null, 'UCF', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (70, 267, null, 'UCP', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (81, 413, null, 'NZHPT', null);
insert into LAB_SECTION (LAB_SECTION_ID, LAB_ID, NAME, CODE, CLOSED) values (71, 273, null, 'SUP', null);

insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (210, 'burrowed', 'U', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (211, 'concretionary', 'O', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (212, 'rock fragments', 'R', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (213, 'highly quartzose', 'Q', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (214, 'feldspathic', 'X', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (901, 'NZMS1 <1975', null, 'first version of fossil record form (SIR(GS)4).  Converted to NZMS260', 'DataOrigin');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (902, 'NZMS1 1975-1980', null, 'form GSNZ-F1. Converted to NZMS260', 'DataOrigin');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (903, 'NZMS260 <1984', null, 'form GSNZ-2A', 'DataOrigin');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (904, '1984-1991', null, 'terminal entry on VAX - SQD database', 'DataOrigin');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (905, '>1991 terminal', null, 'terminal entry on VAX - BASIS database', 'DataOrigin');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (906, '>1991 foreign', null, 'foreign data entry -> BASIS', 'DataOrigin');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (908, '>=2003', null, 'Client/server - Oracle database', 'DataOrigin');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (222, 'radiocarbon', null, null, 'FossilGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (223, 'macrofauna', null, null, 'FossilGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (224, 'microfauna', null, null, 'FossilGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (225, 'microflora', null, null, 'FossilGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (231, 'nearby', null, null, 'SampRel');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (232, 'above', null, null, 'SampRel');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (233, 'below', null, null, 'SampRel');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (236, 'above top', null, null, 'StratRel');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (237, 'above base', null, null, 'StratRel');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (238, 'below top', null, null, 'StratRel');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (239, 'below base', null, null, 'StratRel');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (301, 'BACILLARIOPHYCEAE', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (302, 'CHLOROPHYCEAE', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (303, 'DINOPHYCEAE', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (304, 'PRASINOPHYCEAE', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (209, 'shelly', 'S', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (11, 'Cutting', null, null, 'DrillType');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (12, 'Core', null, null, 'DrillType');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (101, 'boulder', 'B', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (102, 'cobble', 'C', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (103, 'pebble', 'P', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (104, 'granule', '1', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (105, 'very coarse sand', '2', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (106, 'coarse sand', '3', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (107, 'medium sand', '4', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (108, 'fine sand', '5', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (109, 'very fine sand', '6', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (110, 'silt', '7', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (111, 'clay', '8', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (112, 'mud', '9', null, 'GrainSize');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (121, 'non-bedded', '1', null, 'BedThick');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (122, '> 120 cm', '2', null, 'BedThick');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (123, '60 - 120 cm', '3', null, 'BedThick');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (124, '5 - 60 cm', '4', null, 'BedThick');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (125, '1 - 5 cm', '5', null, 'BedThick');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (126, '< 1 cm (laminated)', '6', null, 'BedThick');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (131, 'graded', 'G', null, 'Bedding');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (132, 'slump-folded', 'S', null, 'Bedding');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (133, 'cross-bedded', 'X', null, 'Bedding');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (141, 'none or slight', '1', null, 'Weathering');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (142, 'moderate', '2', null, 'Weathering');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (143, 'intense', '3', null, 'Weathering');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (151, 'unconsolidated', '1', null, 'Hardness');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (152, 'moderately soft', '2', null, 'Hardness');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (153, 'moderately hard', '3', null, 'Hardness');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (154, 'hard', '4', null, 'Hardness');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (161, 'non-calcareous', '1', null, 'Carbonate');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (162, 'calcareous', '2', null, 'Carbonate');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (163, 'limestone', '3', null, 'Carbonate');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (171, 'light', 'L', null, 'ColourMod');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (172, 'medium', 'M', null, 'ColourMod');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (173, 'dark', 'D', null, 'ColourMod');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (181, 'white', '1', null, 'RockColour');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (182, 'grey', '2', null, 'RockColour');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (183, 'black', '3', null, 'RockColour');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (184, 'red', '4', null, 'RockColour');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (185, 'brown', '5', null, 'RockColour');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (186, 'yellow', '6', null, 'RockColour');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (187, 'green', '7', null, 'RockColour');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (188, 'blue', '8', null, 'RockColour');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (189, 'purple', '9', null, 'RockColour');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (201, 'carbonaceous', 'C', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (202, 'glauconitic', 'G', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (203, 'micaceous', 'M', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (204, 'phosphatic', 'F', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (205, 'pyritic', 'P', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (206, 'tuffaceous', 'T', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (207, 'sulphurous', 'Z', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (208, 'bentonitic', 'B', null, 'SedFeature');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (52, 'Edit', '2', null, 'FolderRight');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (53, 'Create', '4', null, 'FolderRight');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (54, 'Delete', '8', null, 'FolderRight');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (55, 'Submit', '16', null, 'FolderRight');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (56, 'Admin', '32', null, 'FolderRight');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (51, 'Read', '1', null, 'FolderRight');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (57, 'Approve', '64', null, 'FolderRight');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (305, 'XANTHOPHYCEAE', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (306, 'CALCAREOUS NANNOPLANKTON', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (307, 'SILICEOUS NANNOPLANKTON', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (308, 'ALGAE', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (309, 'ACRITARCHA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (400, 'Mainland NZ', 'NZ', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (401, 'Chatham Islands', 'CH', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (402, 'Ross Sea', 'RS', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (403, 'New Caledonia', 'NC', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (404, 'Tokelau', 'TL', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (405, 'Fiji', 'FJ', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (406, 'Samoa', 'SA', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (407, 'Niue', 'NU', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (408, 'Cook Islands', 'CK', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (409, 'Norfolk Island', 'NR', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (410, 'Tonga', 'TG', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (411, 'Lord Howe Island', 'LH', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (412, 'Kermadec Islands', 'KE', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (413, 'Bounty Islands', 'BT', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (414, 'The Snares', 'SN', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (415, 'Campbell Island', 'CA', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (416, 'Auckland Islands', 'AK', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (417, 'Antipodes Island', 'AP', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (418, 'Macquarie Island', 'MQ', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (419, 'Other', 'OT', null, 'RegArea');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (310, 'FUNGI', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (311, 'SPORITES', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (312, 'POLLENITES', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (313, 'PLANTAE', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (314, 'FORAMINIFERA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (315, 'RHIZOPODA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (316, 'RADIOLARIA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (317, 'PROTOZOA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (318, 'PORIFERA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (319, 'ARCHAEOCYATHINA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (320, 'COELENTERATA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (321, 'BRYOZOA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (322, 'BRACHIOPODA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (323, 'BIVALVIA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (324, 'GASTROPODA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (325, 'SCAPHOPODA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (326, 'POLYPLACOPHORA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (327, 'NAUTILOIDEA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (328, 'AMMONOIDEA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (329, 'COLEOIDEA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (330, 'CEPHALOPODA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (331, 'MOLLUSCA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (332, 'ANNELIDA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (333, 'POGONOPHORA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (334, 'TRILOBITA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (335, 'OSTRACODA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (336, 'INSECTA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (337, 'ARTHROPODA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (338, 'CRINOIDEA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (339, 'ASTEROIDEA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (340, 'ECHINOIDEA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (341, 'ECHINODERMATA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (342, 'HEMICHORDATA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (343, 'REPTILIA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (344, 'CHONDRICHTHYES', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (345, 'OSTEICHTHYES', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (346, 'AVES', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (347, 'MAMMALIA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (348, 'CONODONTA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (349, 'ICHNOFOSSILS', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (350, 'COPROLITES', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (356, 'CHORDATA', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (357, 'INCERTAE SEDIS', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (358, 'BIOSTATISTICS', null, null, 'TaxaGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (907, 'FRF-GR', null, 'Localities only - captured from paper records', 'DataOrigin');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (13, 'Exposure', null, null, 'DrillType');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (14, 'Junk Basket', null, null, 'DrillType');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (15, 'Sidewall', null, null, 'DrillType');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (16, 'Miscell', null, null, 'DrillType');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (21, 'Registered Users', null, null, 'SecurityClass');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (22, 'User', null, null, 'SecurityClass');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (23, 'User + GNS Paleo', null, null, 'SecurityClass');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (25, 'Org + GNS Paleo', null, null, 'SecurityClass');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (24, 'Organisation', null, null, 'SecurityClass');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (227, 'macroflora', null, null, 'FossilGroup');
insert into LOOKUP (LOOKUP_ID, NAME, CODE, DESCRIPTION, FIELDNAME) values (226, 'other', null, null, 'FossilGroup');


insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (400, 'Mainland NZ', 'NZ');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (401, 'Chatham Islands', 'CH');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (402, 'Ross Sea', 'RS');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (403, 'New Caledonia', 'NC');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (404, 'Tokelau', 'TL');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (405, 'Fiji', 'FJ');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (406, 'Samoa', 'SA');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (407, 'Niue', 'NU');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (408, 'Cook Islands', 'CK');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (409, 'Norfolk Island', 'NR');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (410, 'Tonga', 'TG');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (411, 'Lord Howe Island', 'LH');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (412, 'Kermadec Islands', 'KE');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (413, 'Bounty Islands', 'BT');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (414, 'The Snares', 'SN');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (415, 'Campbell Island', 'CA');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (416, 'Auckland Islands', 'AK');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (417, 'Antipodes Island', 'AP');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (418, 'Macquarie Island', 'MQ');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (419, 'Offshore/Other', 'OT');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (420, 'Vanuatu', 'VA');
insert into REGISTRATION_AREA (REG_AREA_ID, NAME, CODE) values (421, 'Papua New Guinea', 'PG');

insert into RELATIONSHIP_TYPE (RELTYPE_ID, NAME, RELATION_TYPE) values (231, 'nearby', 'Sample');
insert into RELATIONSHIP_TYPE (RELTYPE_ID, NAME, RELATION_TYPE) values (232, 'above', 'Sample');
insert into RELATIONSHIP_TYPE (RELTYPE_ID, NAME, RELATION_TYPE) values (233, 'below', 'Sample');
insert into RELATIONSHIP_TYPE (RELTYPE_ID, NAME, RELATION_TYPE) values (236, 'above top', 'Stratigraphic');
insert into RELATIONSHIP_TYPE (RELTYPE_ID, NAME, RELATION_TYPE) values (237, 'above base', 'Stratigraphic');
insert into RELATIONSHIP_TYPE (RELTYPE_ID, NAME, RELATION_TYPE) values (238, 'below top', 'Stratigraphic');
insert into RELATIONSHIP_TYPE (RELTYPE_ID, NAME, RELATION_TYPE) values (239, 'below base', 'Stratigraphic');

insert into ROCK_COLOUR (COLOUR_ID, NAME, CODE) values (181, 'white', '1');
insert into ROCK_COLOUR (COLOUR_ID, NAME, CODE) values (182, 'grey', '2');
insert into ROCK_COLOUR (COLOUR_ID, NAME, CODE) values (183, 'black', '3');
insert into ROCK_COLOUR (COLOUR_ID, NAME, CODE) values (184, 'red', '4');
insert into ROCK_COLOUR (COLOUR_ID, NAME, CODE) values (185, 'brown', '5');
insert into ROCK_COLOUR (COLOUR_ID, NAME, CODE) values (186, 'yellow', '6');
insert into ROCK_COLOUR (COLOUR_ID, NAME, CODE) values (187, 'green', '7');
insert into ROCK_COLOUR (COLOUR_ID, NAME, CODE) values (188, 'blue', '8');
insert into ROCK_COLOUR (COLOUR_ID, NAME, CODE) values (189, 'purple', '9');


insert into SECURITY_CLASS (CLASS_ID, NAME) values (21, 'Registered Users');
insert into SECURITY_CLASS (CLASS_ID, NAME) values (22, 'User');
insert into SECURITY_CLASS (CLASS_ID, NAME) values (23, 'User + GNS Paleo');
insert into SECURITY_CLASS (CLASS_ID, NAME) values (25, 'Org + GNS Paleo');
insert into SECURITY_CLASS (CLASS_ID, NAME) values (24, 'Organisation');

insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (210, 'burrowed', 'U');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (211, 'concretionary', 'O');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (212, 'rock fragments', 'R');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (213, 'highly quartzose', 'Q');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (214, 'feldspathic', 'X');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (209, 'shelly', 'S');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (201, 'carbonaceous', 'C');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (202, 'glauconitic', 'G');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (203, 'micaceous', 'M');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (204, 'phosphatic', 'F');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (205, 'pyritic', 'P');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (206, 'tuffaceous', 'T');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (207, 'sulphurous', 'Z');
insert into SEDIMENTARY_FEATURE_TYPE (SEDFEATURE_TYPE_ID, NAME, CODE) values (208, 'bentonitic', 'B');


insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (301, 'Bacillariophyceae');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (302, 'Chlorophyceae');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (303, 'Dinophyceae');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (304, 'Prasinophyceae');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (305, 'Xanthophyceae');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (306, 'Calcareous Nannoplankton');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (307, 'Siliceous Nannoplankton');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (308, 'Algae');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (309, 'Acritarcha');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (310, 'Fungi');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (311, 'Sporites');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (312, 'Pollenites');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (313, 'Plantae');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (314, 'Foraminifera');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (315, 'Rhizopoda');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (316, 'Radiolaria');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (317, 'Protozoa');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (318, 'Porifera');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (319, 'Archaeocyathina');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (320, 'Cnidaria');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (321, 'Bryozoa');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (322, 'Brachiopoda');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (323, 'Bivalvia');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (324, 'Gastropoda');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (325, 'Scaphopoda');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (326, 'Polyplacophora');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (327, 'Nautiloidea');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (328, 'Ammonoidea');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (329, 'Coleoidea');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (330, 'Cephalopoda');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (331, 'Mollusca');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (332, 'Annelida');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (334, 'Trilobita');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (335, 'Ostracoda');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (336, 'Insecta');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (337, 'Arthropoda');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (338, 'Crinoidea');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (339, 'Asteroidea');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (340, 'Echinoidea');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (341, 'Echinodermata');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (342, 'Hemichordata');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (343, 'Reptilia');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (344, 'Chondrichthyes');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (345, 'Osteichthyes');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (346, 'Aves');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (347, 'Mammalia');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (348, 'Conodonta');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (349, 'Ichnofossils');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (350, 'Coprolites');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (356, 'Chordata');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (357, 'Incertae Sedis');
insert into TAXONOMIC_GROUP (GROUP_ID, NAME) values (358, 'Biostatistics');


insert into WEATHERING (WEATHERING_ID, NAME, CODE) values (141, 'none or slight', '1');
insert into WEATHERING (WEATHERING_ID, NAME, CODE) values (142, 'moderate', '2');
insert into WEATHERING (WEATHERING_ID, NAME, CODE) values (143, 'intense', '3');
