CREATE TABLE Person
(
Person_ID	NUMBER(5),
Name	VARCHAR2(64) NOT NULL,
ST_Code	NUMBER(4),
PRIMARY KEY (Person_ID),
CONSTRAINT ST_FK FOREIGN KEY (ST_Code) REFERENCES MIS.GNS_Staff (ST_Code)
);

CREATE INDEX person_IDX1 ON PERSON (name) TABLESPACE INDX;
CREATE INDEX Person_IDX2 ON Person (ST_Code) TABLESPACE INDX;