<!-- ============================================================== -->
<!-- Run Middlegen -->
<!-- ============================================================== -->
<project name="fred" default="middlegen">
<target name="middlegen" >
  <mkdir dir="hibernate"/>
 	
  <taskdef
    name="middlegen"
    classname="middlegen.MiddlegenTask"
  	classpath="c:\lib\middlegen-2.1.jar;c:\lib\middlegen-hibernate-plugin-2.1.jar;c:\lib\commons-collections-3.1.jar;c:\lib\velocity-1.4.jar;c:\lib\log4j-1.2.9.jar" 
  />

  <middlegen
    appname="fred"
    databaseurl="jdbc:oracle:thin:fr/ossify@raptor.gns.cri.nz:1521:dev"
    driver="oracle.jdbc.OracleDriver"
    schema="fr"
  >

     <!-- Plugins -->
     <hibernate
        destination="hibernate"
        package="nz.cri.gns.fred.hibernate"
        javaTypeMapper="middlegen.plugins.hibernate.HibernateJavaTypeMapper"
     />

   </middlegen>
	
	<delete file="velocity.log" />
</target>
</project>