package nz.cri.gns.fred.model;

import java.util.Date;
import java.util.Set;

public interface Sample extends Audited, Comparable<Sample> {
	
	public Integer getSampleId();
	public void setSampleId(Integer sampleId);
	public Double getTopDepth();
	public void setTopDepth(Double topDepth);
	public Double getBottomDepth();
	public void setBottomDepth(Double bottomDepth);
	public String getDepthUnit();
	public void setDepthUnit(String depthUnit);
	public String getComments();
	public void setComments(String comments);
	public Date getCollectionDate();
	public void setCollectionDate(Date collectionDate);
	public String getDateRounding();
	public void setDateRounding(String dateRounding);
	public String getStratUnit();
	public void setStratUnit(String stratUnit);
	public String getInPlace();
	public void setInPlace(String inPlace);
	public String getNotCollected();
	public void setNotCollected(String notCollected);
	public String getSignificance();
	public void setSignificance(String significance);
	public String getColumnMap();
	public void setColumnMap(String columnMap);
	public Integer getDip();
	public void setDip(Integer dip);
	public String getDipDirection();
	public void setDipDirection(String dipDirection);
	public Integer getStrike();
	public void setStrike(Integer strike);
	public String getFacing();
	public void setFacing(String facing);
	public String getStratComments();
    public void setStratComments(String stratComments);
	public String getComparatorUsed();
	public void setComparatorUsed(String comparatorUsed);
	public String getWet();
	public void setWet(String wet);
	public String getRockNature();
	public void setRockNature(String rockNature);
	public String getDepositionEnv();
	public void setDepositionEnv(String depositionEnv);
	public String getCorrespondence();
	public void setCorrespondence(String correspondence);
	public ColourModifier getColourModifier();
	public void setColourModifier(ColourModifier colourModifier);
	public Hardness getHardness();
	public void setHardness(Hardness hardness);
	public Weathering getWeathering();
	public void setWeathering(Weathering weathering);
	public Carbonate getCarbonate();
	public void setCarbonate(Carbonate carbonate);
	public RockColour getSecondaryColour();
	public void setSecondaryColour(RockColour rockColourBySecondaryColourId);
	public RockColour getPrimaryColour();
	public void setPrimaryColour(RockColour rockColourByPrimaryColourId);
	public Feature getFeature();
	public void setFeature(Feature feature);
	public Bedding getPrimaryBedding();
	public void setPrimaryBedding(Bedding beddingByPrimaryBeddingId);
	public Bedding getSecondaryBedding();
	public void setSecondaryBedding(Bedding beddingBySecondaryBeddingId);
	public FrNumber getFrNumber();
	public void setFrNumber(FrNumber frNumber);
	public FrNumber getYardFrNumber();
	public void setYardFrNumber(FrNumber yardFrNumber);
	public DrillType getDrillType();
	public void setDrillType(DrillType drillType);
	public GrainSize getPrimaryGrainSize();
	public void setPrimaryGrainSize(GrainSize grainSizeByPrimaryGrainsizeId);
	public GrainSize getSecondaryGrainSize();
	public void setSecondaryGrainSize(GrainSize grainSizeBySecondaryGrainSize);
	public BedThickness getBedThickness();
	public void setBedThickness(BedThickness bedThickness);
	public Stage getKnownStage();
	public void setKnownStage(Stage stageByKnownStageId);
	public Stage getInferredStage();
	public void setInferredStage(Stage stageByInferredStageId);
	public Set<SedimentaryFeature> getSedimentaryFeatures();
	public void setSedimentaryFeatures(Set<SedimentaryFeature> sedimentaryFeatures);
    public Set<MetaCat> getMetaCats();
    public void setMetaCats(Set<MetaCat> metaCats);
	public Set<Record> getRecords();
	public void setRecords(Set<Record> records);
	public Set<SentTo> getSentTos();
	public void setSentTos(Set<SentTo> sentTos);
	public Set<Person> getCollectors();
	public void setCollectors(Set<Person> collectors);
	public Set<Relationship> getRelationships();
	public void setRelationships(Set<Relationship> relationships);
	
}