/*
 * A context driven hint.
 * 
 * The url generated by urlGenerator must return an XML document with a 'name' 
 * element eg ...<name>Bob</name>....<name>Gertrude</name>...
 * which will be used for the hints
 */
/*
 * Constructor takes a field activatorField which will be the element
 * from which the thing is triggered, and a function urlGenerator which
 * when given the starting text will generate the AJAX url
 */
ContextHint = function(activatorField, urlGenerator, omitFieldFix) {
    this.field = activatorField;
    this.generator = urlGenerator;
    this.isIE = navigator.appName.indexOf("Internet Expl") > -1;
    this.hintVisible = false;
    this.selectedHint = -1;
    this.maximumHint = 0;
    this.key = activatorField.id;
    
    //Store 
    contextHints[this.key] = this;
    
    //Setup the field
    eval("activatorField.onblur = function() {getContextHint('" + this.key + "').hideDropout();};");
	ContextHint.addEvent(this.field, "keyup", ContextHint.processUnknownKeyStroke);
	//eval("activatorField.onkeyup = function() {getContextHint('" + this.key + "').processKeyStroke();};");
    
    //Write the div
    document.write('<div id="' + this.key + 'Hint" scroll="none" style="z-index: 10; border: solid 1pt black; visibility: hidden; position: absolute"></div>');
    
    this.hintDiv = document.getElementById(this.key + "Hint");

    //Make sure the field is appropriately setup
    this.field.setAttribute("autocomplete", "OFF");
    //Write ie fixes
    if (this.isIE) {
    	document.write('<iframe id="' + this.key + 'Frame" style="z-index: 9; position:absolute; visibility: hidden; scroll: none"></iframe>');
    	this.hintFrame = document.getElementById(this.key + "Frame");
    }
	//This is to stop forms from submitting on hitting enter
	if (!omitFieldFix && !document.getElementById("hintSubmitStop")) {
	    var stopElement = document.createElement("input");
	    stopElement.type = "hidden";
	    stopElement.value = "0";
	    stopElement.id = "hintSubmitStop";
 	    stopElement.name = "hintSubmitStop";
	    var frm = this.field.form;
	    frm.appendChild(stopElement);
	    frm.onsubmit = function() {
	        return (document.getElementById("hintSubmitStop").value != 0);
	    };
	    var formElements = frm.elements;

	    for (i=0; i<formElements.length; i++) {
	        if (formElements[i].type == 'submit' || formElements[i].type == 'image') {
                formElements[i].onmouseover = function() {
                    document.getElementById("hintSubmitStop").value = "1";
                };
                formElements[i].onmouseout = function() {
                    document.getElementById("hintSubmitStop").value = "0";
                };
	        }
	    }
    }

this.processKeyStroke = function(keyCode) {
	
	switch (keyCode) {
		case 27:	//Escape
			this.hideDropout(false);
			break;
		case 38:	//Up arrow
			this.highlightUp();
			break;
		case 40:	//Down arrow
			this.highlightDown();
			break;
		case 13:
		    if (this.selectedHint > -1)
		        this.updateFromKeyEvent();
			break;
		default:
			this.processHint();
			break;
	}
};

this.unHighlightHint = function(hint) {
	if (hint >= 0) {
		oldObj = document.getElementById(this.key + "Hint" + hint);
		oldObj.style.background = ((hint % 2) == 0) ? "white" : "#eeeeee";
		oldObj.style.color = "black";
	}
};

this.highlightHint = function(hint) {
	newObj = document.getElementById(this.key + "Hint" + hint);
	newObj.style.background = "darkblue";
	newObj.style.color = "white";
};

this.highlightDown = function() {
	this.unHighlightHint(this.selectedHint);

	this.selectedHint += 1;
	if (this.selectedHint >= this.maximumHint)
		this.selectedHint = 0;
		
	this.highlightHint(this.selectedHint);
};

this.highlightUp = function() {
	this.unHighlightHint(this.selectedHint);

	this.selectedHint -= 1;
	if (this.selectedHint <0)
		this.selectedHint = this.maximumHint - 1;
		
	this.highlightHint(this.selectedHint);
};

this.updateFromKeyEvent = function() {
	this.updateField(document.getElementById(this.key + "Hint" + this.selectedHint).hintValue);
};

//"ajaxSupport.xml?type=Person&start=" + val + "&q=" + Math.random()
this.processHint = function() {
	var val = this.field.value;
	if (val.length == 0)
		this.hideDropout();
	else
		eval("callAJAX(urlGenerator(val), function() {showHints('" + this.key + "')});");
};

this.showHint = function() {
	if (xmlHttp.readyState == 4 || xmlHttp.readyState == "complete") {
		var xml = xmlHttp.responseXML;
		this.hintDiv.innerHTML = "";
		this.createAndShowTable(xml);
	}
};

this.createAndShowTable = function(xml) {
	var names = xml.getElementsByTagName("name");
	if (names.length == 0) {
		this.hideDropout(true);
		return;
	}
	for (var i=0; i<names.length; i++) {
		var hint = names[i].firstChild.data;
		var cell = document.createElement("div");
		if (i % 2 == 0)
			cell.style.background = "white";
		else
			cell.style.background = "#eeeeee";
		cell.id = this.key + "Hint" + i;
		cell.hintValue = hint;
		cell.innerHTML = hint;
		cell.style.paddingRight = "5px";
		cell.style.paddingLeft = "5px";
		cell.style.whiteSpace = "nowrap";
		cell.style.cursor = "default";
		eval("cell.onclick = function() {getContextHint('" + this.key + "').updateField('" + hint + "');}");
		this.hintDiv.appendChild(cell);
	}
	//Reset the selected settings
	this.selectedHint = -1;
	this.maximumHint = names.length;
	
	if (!this.hintVisible)
		this.showDropout();
	else if (this.isIE) {
	    this.showDropout(true);
	}
};

this.updateField = function(value) {
	this.field.value = value;
	this.hideDropout(true);
	this.field.focus();
};

this.showDropout = function(immediate) {
	this.hintDiv.style.left = getXPos(this.field) + "px";
	this.hintDiv.style.top = (getYPos(this.field) + this.field.offsetHeight) + "px";

	if (this.isIE) {
		this.showIEFix();
	}

    if (immediate) {
        fadeIn(this.key + "Hint", 99.999);
    } else {
	    fadeIn(this.key + "Hint", 0);
	}
	this.hintDiv.style.visibility = "visible";
	this.hintVisible = true;
};

this.showIEFix = function() {
	this.hintFrame.style.visibility = "visible";
	this.hintFrame.style.left = this.hintDiv.style.left;
	this.hintFrame.style.top = this.hintDiv.style.top;
	this.hintFrame.style.width = this.hintDiv.offsetWidth + "px";
	this.hintFrame.style.height = this.hintDiv.offsetHeight + "px";
	this.hintFrame.style.zIndex = 9;
	this.hintDiv.style.visibility = "visible";
	this.hintDiv.style.zIndex = 10;
};

this.hideDropout = function(immediate) {
	if (immediate) {
		this.hintDiv.style.visibility = "hidden";
	} else {
		fadeOut(this.key + "Hint", 90);
	}
	this.hintVisible = false;
	if (this.isIE) 
		this.hintFrame.style.visibility = "hidden";
};


} //END OF OBJECT DEFINITION

ContextHint.addEvent = function(element, evname, func) {
	if (element.attachEvent) { // IE
		element.attachEvent("on" + evname, func);
	} else if (element.addEventListener) { // Gecko / W3C
		element.addEventListener(evname, func, true);
	} else {
		element["on" + evname] = func;
	}
};




//An array of context hints that are used in this page
var contextHints = new Object();

//Global/static method to find a context hint
function getContextHint(id) {
    return contextHints[id];
}

function showHints(key) {
    getContextHint(key).showHint();
}

ContextHint.processUnknownKeyStroke = function(event) {
	//For ie....
	(this.isIE) && (event = window.event);
	
	var keyCode = (document.layers) ? keyStroke.which : event.keyCode;
	
	getContextHint(((event.srcElement) ? event.srcElement : event.target).id).processKeyStroke(keyCode);
}

