CREATE OR REPLACE TRIGGER Folder_Seq_Trg
BEFORE INSERT ON Folder
REFERENCING NEW AS new
FOR EACH ROW
WHEN (new.Folder_ID IS NULL)
DECLARE
  ok INTEGER;
  newID NUMBER;
BEGIN
  ok := 1;
  WHILE ok > 0 LOOP
    SELECT Folder_Seq.NEXTVAL INTO newID FROM DUAL;
    SELECT COUNT(*) INTO ok FROM Folder WHERE Folder_ID = newID;
  END LOOP;
  :NEW.Folder_ID := newID;
END;
/