<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <groupId>nz.cri.gns.fred</groupId>
        <artifactId>fred-top</artifactId>
        <version>3.4.2</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>nz.cri.gns.fred</groupId>
    <artifactId>fred-integration</artifactId>
    <packaging>jar</packaging>
    <name>FRED Integration Tests</name>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>4.13.2</junit.version>
        <junit.jupiter.version>5.0.0-M4</junit.jupiter.version>
        <junit.vintage.version>${junit.version}.0-M4</junit.vintage.version>
        <junit.platform.version>1.0.0-M4</junit.platform.version>
    </properties>
    
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit47</artifactId>
                        <version>2.12</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit47</artifactId>
                        <version>2.22.2</version>
                    </dependency>
                </dependencies>
                <!--
                <configuration>
                    <groups>nz.cri.gns.test.IntegrationTest</groups>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                        <configuration>
                            <includes>
                                <include>**/*.class</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>-->
            </plugin>   
        </plugins>
    </build>
    <dependencies>
         
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>servlet-api</artifactId>
            <version>2.3</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.13</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.13</version>
        </dependency>
        
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.189</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>nz.cri.gns</groupId>
            <artifactId>fred</artifactId>
            <version>${project.version}</version>
            <classifier>classes</classifier>
            <type>jar</type>
            <scope>test</scope>
        </dependency>


        <dependency>
            <groupId>nz.cri.gns</groupId>
            <artifactId>munginator</artifactId>
            <version>0.1.0.4</version>
        </dependency>
        
        <dependency>
            <groupId>nz.cri.gns.online-servlet</groupId>
            <artifactId>online-servlet-core</artifactId>
            <version>3.2.3</version>
        </dependency>
        
    </dependencies>

</project>
